// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// NotifyRule is the predicate function for notifyrule builders.
type NotifyRule func(*sql.Selector)

// PendingOp is the predicate function for pendingop builders.
type PendingOp func(*sql.Selector)

// Thread is the predicate function for thread builders.
type Thread func(*sql.Selector)
