// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/arqueon/dankmail/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// ProviderMessageID applies equality check predicate on the "provider_message_id" field. It's identical to ProviderMessageIDEQ.
func ProviderMessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldProviderMessageID, v))
}

// Rfc822MessageID applies equality check predicate on the "rfc822_message_id" field. It's identical to Rfc822MessageIDEQ.
func Rfc822MessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRfc822MessageID, v))
}

// From applies equality check predicate on the "from" field. It's identical to FromEQ.
func From(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFrom, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldDate, v))
}

// Snippet applies equality check predicate on the "snippet" field. It's identical to SnippetEQ.
func Snippet(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSnippet, v))
}

// BodyText applies equality check predicate on the "body_text" field. It's identical to BodyTextEQ.
func BodyText(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldBodyText, v))
}

// ProviderMessageIDEQ applies the EQ predicate on the "provider_message_id" field.
func ProviderMessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldProviderMessageID, v))
}

// ProviderMessageIDNEQ applies the NEQ predicate on the "provider_message_id" field.
func ProviderMessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldProviderMessageID, v))
}

// ProviderMessageIDIn applies the In predicate on the "provider_message_id" field.
func ProviderMessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldProviderMessageID, vs...))
}

// ProviderMessageIDNotIn applies the NotIn predicate on the "provider_message_id" field.
func ProviderMessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldProviderMessageID, vs...))
}

// ProviderMessageIDGT applies the GT predicate on the "provider_message_id" field.
func ProviderMessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldProviderMessageID, v))
}

// ProviderMessageIDGTE applies the GTE predicate on the "provider_message_id" field.
func ProviderMessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldProviderMessageID, v))
}

// ProviderMessageIDLT applies the LT predicate on the "provider_message_id" field.
func ProviderMessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldProviderMessageID, v))
}

// ProviderMessageIDLTE applies the LTE predicate on the "provider_message_id" field.
func ProviderMessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldProviderMessageID, v))
}

// ProviderMessageIDContains applies the Contains predicate on the "provider_message_id" field.
func ProviderMessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldProviderMessageID, v))
}

// ProviderMessageIDHasPrefix applies the HasPrefix predicate on the "provider_message_id" field.
func ProviderMessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldProviderMessageID, v))
}

// ProviderMessageIDHasSuffix applies the HasSuffix predicate on the "provider_message_id" field.
func ProviderMessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldProviderMessageID, v))
}

// ProviderMessageIDEqualFold applies the EqualFold predicate on the "provider_message_id" field.
func ProviderMessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldProviderMessageID, v))
}

// ProviderMessageIDContainsFold applies the ContainsFold predicate on the "provider_message_id" field.
func ProviderMessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldProviderMessageID, v))
}

// Rfc822MessageIDEQ applies the EQ predicate on the "rfc822_message_id" field.
func Rfc822MessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRfc822MessageID, v))
}

// Rfc822MessageIDNEQ applies the NEQ predicate on the "rfc822_message_id" field.
func Rfc822MessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldRfc822MessageID, v))
}

// Rfc822MessageIDIn applies the In predicate on the "rfc822_message_id" field.
func Rfc822MessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldRfc822MessageID, vs...))
}

// Rfc822MessageIDNotIn applies the NotIn predicate on the "rfc822_message_id" field.
func Rfc822MessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldRfc822MessageID, vs...))
}

// Rfc822MessageIDGT applies the GT predicate on the "rfc822_message_id" field.
func Rfc822MessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldRfc822MessageID, v))
}

// Rfc822MessageIDGTE applies the GTE predicate on the "rfc822_message_id" field.
func Rfc822MessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldRfc822MessageID, v))
}

// Rfc822MessageIDLT applies the LT predicate on the "rfc822_message_id" field.
func Rfc822MessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldRfc822MessageID, v))
}

// Rfc822MessageIDLTE applies the LTE predicate on the "rfc822_message_id" field.
func Rfc822MessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldRfc822MessageID, v))
}

// Rfc822MessageIDContains applies the Contains predicate on the "rfc822_message_id" field.
func Rfc822MessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldRfc822MessageID, v))
}

// Rfc822MessageIDHasPrefix applies the HasPrefix predicate on the "rfc822_message_id" field.
func Rfc822MessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldRfc822MessageID, v))
}

// Rfc822MessageIDHasSuffix applies the HasSuffix predicate on the "rfc822_message_id" field.
func Rfc822MessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldRfc822MessageID, v))
}

// Rfc822MessageIDEqualFold applies the EqualFold predicate on the "rfc822_message_id" field.
func Rfc822MessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldRfc822MessageID, v))
}

// Rfc822MessageIDContainsFold applies the ContainsFold predicate on the "rfc822_message_id" field.
func Rfc822MessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldRfc822MessageID, v))
}

// FromEQ applies the EQ predicate on the "from" field.
func FromEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFrom, v))
}

// FromNEQ applies the NEQ predicate on the "from" field.
func FromNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldFrom, v))
}

// FromIn applies the In predicate on the "from" field.
func FromIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldFrom, vs...))
}

// FromNotIn applies the NotIn predicate on the "from" field.
func FromNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldFrom, vs...))
}

// FromGT applies the GT predicate on the "from" field.
func FromGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldFrom, v))
}

// FromGTE applies the GTE predicate on the "from" field.
func FromGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldFrom, v))
}

// FromLT applies the LT predicate on the "from" field.
func FromLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldFrom, v))
}

// FromLTE applies the LTE predicate on the "from" field.
func FromLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldFrom, v))
}

// FromContains applies the Contains predicate on the "from" field.
func FromContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldFrom, v))
}

// FromHasPrefix applies the HasPrefix predicate on the "from" field.
func FromHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldFrom, v))
}

// FromHasSuffix applies the HasSuffix predicate on the "from" field.
func FromHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldFrom, v))
}

// FromEqualFold applies the EqualFold predicate on the "from" field.
func FromEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldFrom, v))
}

// FromContainsFold applies the ContainsFold predicate on the "from" field.
func FromContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldFrom, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldDate, v))
}

// SnippetEQ applies the EQ predicate on the "snippet" field.
func SnippetEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSnippet, v))
}

// SnippetNEQ applies the NEQ predicate on the "snippet" field.
func SnippetNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSnippet, v))
}

// SnippetIn applies the In predicate on the "snippet" field.
func SnippetIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSnippet, vs...))
}

// SnippetNotIn applies the NotIn predicate on the "snippet" field.
func SnippetNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSnippet, vs...))
}

// SnippetGT applies the GT predicate on the "snippet" field.
func SnippetGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSnippet, v))
}

// SnippetGTE applies the GTE predicate on the "snippet" field.
func SnippetGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSnippet, v))
}

// SnippetLT applies the LT predicate on the "snippet" field.
func SnippetLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSnippet, v))
}

// SnippetLTE applies the LTE predicate on the "snippet" field.
func SnippetLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSnippet, v))
}

// SnippetContains applies the Contains predicate on the "snippet" field.
func SnippetContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSnippet, v))
}

// SnippetHasPrefix applies the HasPrefix predicate on the "snippet" field.
func SnippetHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSnippet, v))
}

// SnippetHasSuffix applies the HasSuffix predicate on the "snippet" field.
func SnippetHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSnippet, v))
}

// SnippetEqualFold applies the EqualFold predicate on the "snippet" field.
func SnippetEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSnippet, v))
}

// SnippetContainsFold applies the ContainsFold predicate on the "snippet" field.
func SnippetContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSnippet, v))
}

// BodyTextEQ applies the EQ predicate on the "body_text" field.
func BodyTextEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldBodyText, v))
}

// BodyTextNEQ applies the NEQ predicate on the "body_text" field.
func BodyTextNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldBodyText, v))
}

// BodyTextIn applies the In predicate on the "body_text" field.
func BodyTextIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldBodyText, vs...))
}

// BodyTextNotIn applies the NotIn predicate on the "body_text" field.
func BodyTextNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldBodyText, vs...))
}

// BodyTextGT applies the GT predicate on the "body_text" field.
func BodyTextGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldBodyText, v))
}

// BodyTextGTE applies the GTE predicate on the "body_text" field.
func BodyTextGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldBodyText, v))
}

// BodyTextLT applies the LT predicate on the "body_text" field.
func BodyTextLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldBodyText, v))
}

// BodyTextLTE applies the LTE predicate on the "body_text" field.
func BodyTextLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldBodyText, v))
}

// BodyTextContains applies the Contains predicate on the "body_text" field.
func BodyTextContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldBodyText, v))
}

// BodyTextHasPrefix applies the HasPrefix predicate on the "body_text" field.
func BodyTextHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldBodyText, v))
}

// BodyTextHasSuffix applies the HasSuffix predicate on the "body_text" field.
func BodyTextHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldBodyText, v))
}

// BodyTextEqualFold applies the EqualFold predicate on the "body_text" field.
func BodyTextEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldBodyText, v))
}

// BodyTextContainsFold applies the ContainsFold predicate on the "body_text" field.
func BodyTextContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldBodyText, v))
}

// HasThread applies the HasEdge predicate on the "thread" edge.
func HasThread() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ThreadTable, ThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThreadWith applies the HasEdge predicate on the "thread" edge with a given conditions (other predicates).
func HasThreadWith(preds ...predicate.Thread) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
