// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/notifyrule"
	"github.com/arqueon/dankmail/core/ent/pendingop"
	"github.com/arqueon/dankmail/core/ent/thread"
	"github.com/google/uuid"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (_c *AccountCreate) SetType(v account.Type) *AccountCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AccountCreate) SetEmail(v string) *AccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AccountCreate) SetDisplayName(v string) *AccountCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *AccountCreate) SetNillableDisplayName(v *string) *AccountCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *AccountCreate) SetConfig(v map[string]interface{}) *AccountCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetSyncCursor sets the "sync_cursor" field.
func (_c *AccountCreate) SetSyncCursor(v string) *AccountCreate {
	_c.mutation.SetSyncCursor(v)
	return _c
}

// SetNillableSyncCursor sets the "sync_cursor" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSyncCursor(v *string) *AccountCreate {
	if v != nil {
		_c.SetSyncCursor(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountCreate) SetStatus(v account.Status) *AccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountCreate) SetNillableStatus(v *account.Status) *AccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *AccountCreate) SetLastSyncAt(v time.Time) *AccountCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableLastSyncAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *AccountCreate) SetLastError(v string) *AccountCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *AccountCreate) SetNillableLastError(v *string) *AccountCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableID(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddThreadIDs adds the "threads" edge to the Thread entity by IDs.
func (_c *AccountCreate) AddThreadIDs(ids ...int) *AccountCreate {
	_c.mutation.AddThreadIDs(ids...)
	return _c
}

// AddThreads adds the "threads" edges to the Thread entity.
func (_c *AccountCreate) AddThreads(v ...*Thread) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddThreadIDs(ids...)
}

// AddPendingOpIDs adds the "pending_ops" edge to the PendingOp entity by IDs.
func (_c *AccountCreate) AddPendingOpIDs(ids ...int) *AccountCreate {
	_c.mutation.AddPendingOpIDs(ids...)
	return _c
}

// AddPendingOps adds the "pending_ops" edges to the PendingOp entity.
func (_c *AccountCreate) AddPendingOps(v ...*PendingOp) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPendingOpIDs(ids...)
}

// AddNotifyRuleIDs adds the "notify_rules" edge to the NotifyRule entity by IDs.
func (_c *AccountCreate) AddNotifyRuleIDs(ids ...int) *AccountCreate {
	_c.mutation.AddNotifyRuleIDs(ids...)
	return _c
}

// AddNotifyRules adds the "notify_rules" edges to the NotifyRule entity.
func (_c *AccountCreate) AddNotifyRules(v ...*NotifyRule) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotifyRuleIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := account.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := account.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.SyncCursor(); !ok {
		v := account.DefaultSyncCursor
		_c.mutation.SetSyncCursor(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := account.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := account.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := account.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Account.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Account.email"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Account.display_name"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "Account.config"`)}
	}
	if _, ok := _c.mutation.SyncCursor(); !ok {
		return &ValidationError{Name: "sync_cursor", err: errors.New(`ent: missing required field "Account.sync_cursor"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Account.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "Account.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(account.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(account.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.SyncCursor(); ok {
		_spec.SetField(account.FieldSyncCursor, field.TypeString, value)
		_node.SyncCursor = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(account.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(account.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ThreadsTable,
			Columns: []string{account.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PendingOpsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.PendingOpsTable,
			Columns: []string{account.PendingOpsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pendingop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotifyRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.NotifyRulesTable,
			Columns: []string{account.NotifyRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notifyrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	_c.conflict = opts
	return &AccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *AccountUpsert) SetType(v account.Type) *AccountUpsert {
	u.Set(account.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsert) UpdateType() *AccountUpsert {
	u.SetExcluded(account.FieldType)
	return u
}

// SetEmail sets the "email" field.
func (u *AccountUpsert) SetEmail(v string) *AccountUpsert {
	u.Set(account.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountUpsert) UpdateEmail() *AccountUpsert {
	u.SetExcluded(account.FieldEmail)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsert) SetDisplayName(v string) *AccountUpsert {
	u.Set(account.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsert) UpdateDisplayName() *AccountUpsert {
	u.SetExcluded(account.FieldDisplayName)
	return u
}

// SetConfig sets the "config" field.
func (u *AccountUpsert) SetConfig(v map[string]interface{}) *AccountUpsert {
	u.Set(account.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *AccountUpsert) UpdateConfig() *AccountUpsert {
	u.SetExcluded(account.FieldConfig)
	return u
}

// SetSyncCursor sets the "sync_cursor" field.
func (u *AccountUpsert) SetSyncCursor(v string) *AccountUpsert {
	u.Set(account.FieldSyncCursor, v)
	return u
}

// UpdateSyncCursor sets the "sync_cursor" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSyncCursor() *AccountUpsert {
	u.SetExcluded(account.FieldSyncCursor)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountUpsert) SetStatus(v account.Status) *AccountUpsert {
	u.Set(account.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsert) UpdateStatus() *AccountUpsert {
	u.SetExcluded(account.FieldStatus)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *AccountUpsert) SetLastSyncAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *AccountUpsert) UpdateLastSyncAt() *AccountUpsert {
	u.SetExcluded(account.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *AccountUpsert) ClearLastSyncAt() *AccountUpsert {
	u.SetNull(account.FieldLastSyncAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *AccountUpsert) SetLastError(v string) *AccountUpsert {
	u.Set(account.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpsert) UpdateLastError() *AccountUpsert {
	u.SetExcluded(account.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(account.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *AccountUpsertOne) SetType(v account.Type) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateType() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetEmail sets the "email" field.
func (u *AccountUpsertOne) SetEmail(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateEmail() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateEmail()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsertOne) SetDisplayName(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateDisplayName() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetConfig sets the "config" field.
func (u *AccountUpsertOne) SetConfig(v map[string]interface{}) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateConfig() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateConfig()
	})
}

// SetSyncCursor sets the "sync_cursor" field.
func (u *AccountUpsertOne) SetSyncCursor(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSyncCursor(v)
	})
}

// UpdateSyncCursor sets the "sync_cursor" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSyncCursor() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSyncCursor()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpsertOne) SetStatus(v account.Status) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateStatus() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *AccountUpsertOne) SetLastSyncAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateLastSyncAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *AccountUpsertOne) ClearLastSyncAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *AccountUpsertOne) SetLastError(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateLastError() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountUpsertOne.ID is not supported by MySQL driver. Use AccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	_c.conflict = opts
	return &AccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: _c,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(account.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *AccountUpsertBulk) SetType(v account.Type) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateType() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetEmail sets the "email" field.
func (u *AccountUpsertBulk) SetEmail(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateEmail() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateEmail()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *AccountUpsertBulk) SetDisplayName(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateDisplayName() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetConfig sets the "config" field.
func (u *AccountUpsertBulk) SetConfig(v map[string]interface{}) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateConfig() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateConfig()
	})
}

// SetSyncCursor sets the "sync_cursor" field.
func (u *AccountUpsertBulk) SetSyncCursor(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSyncCursor(v)
	})
}

// UpdateSyncCursor sets the "sync_cursor" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSyncCursor() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSyncCursor()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpsertBulk) SetStatus(v account.Status) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateStatus() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *AccountUpsertBulk) SetLastSyncAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateLastSyncAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *AccountUpsertBulk) ClearLastSyncAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *AccountUpsertBulk) SetLastError(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateLastError() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
