// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/contact"
	"github.com/arqueon/dankmail/core/ent/predicate"
	"github.com/google/uuid"
)

// ContactUpdate is the builder for updating Contact entities.
type ContactUpdate struct {
	config
	hooks     []Hook
	mutation  *ContactMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ContactUpdate builder.
func (_u *ContactUpdate) Where(ps ...predicate.Contact) *ContactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *ContactUpdate) SetEmail(v string) *ContactUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableEmail(v *string) *ContactUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContactUpdate) SetName(v string) *ContactUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableName(v *string) *ContactUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ContactUpdate) SetSource(v contact.Source) *ContactUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableSource(v *contact.Source) *ContactUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ContactUpdate) SetWeight(v int) *ContactUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableWeight(v *int) *ContactUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ContactUpdate) AddWeight(v int) *ContactUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *ContactUpdate) SetLastSeen(v time.Time) *ContactUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *ContactUpdate) SetNillableLastSeen(v *time.Time) *ContactUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ContactUpdate) SetAccountID(id uuid.UUID) *ContactUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContactUpdate) SetAccount(v *Account) *ContactUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContactMutation object of the builder.
func (_u *ContactUpdate) Mutation() *ContactMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContactUpdate) ClearAccount() *ContactUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := contact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Contact.source": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Contact.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContactUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContactUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(contact.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(contact.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(contact.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(contact.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(contact.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.AccountTable,
			Columns: []string{contact.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.AccountTable,
			Columns: []string{contact.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContactUpdateOne is the builder for updating a single Contact entity.
type ContactUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ContactMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetEmail sets the "email" field.
func (_u *ContactUpdateOne) SetEmail(v string) *ContactUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableEmail(v *string) *ContactUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContactUpdateOne) SetName(v string) *ContactUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableName(v *string) *ContactUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ContactUpdateOne) SetSource(v contact.Source) *ContactUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableSource(v *contact.Source) *ContactUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ContactUpdateOne) SetWeight(v int) *ContactUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableWeight(v *int) *ContactUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ContactUpdateOne) AddWeight(v int) *ContactUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *ContactUpdateOne) SetLastSeen(v time.Time) *ContactUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *ContactUpdateOne) SetNillableLastSeen(v *time.Time) *ContactUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ContactUpdateOne) SetAccountID(id uuid.UUID) *ContactUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContactUpdateOne) SetAccount(v *Account) *ContactUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContactMutation object of the builder.
func (_u *ContactUpdateOne) Mutation() *ContactMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContactUpdateOne) ClearAccount() *ContactUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ContactUpdate builder.
func (_u *ContactUpdateOne) Where(ps ...predicate.Contact) *ContactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContactUpdateOne) Select(field string, fields ...string) *ContactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Contact entity.
func (_u *ContactUpdateOne) Save(ctx context.Context) (*Contact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContactUpdateOne) SaveX(ctx context.Context) *Contact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContactUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := contact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Contact.source": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Contact.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ContactUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ContactUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ContactUpdateOne) sqlSave(ctx context.Context) (_node *Contact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Contact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contact.FieldID)
		for _, f := range fields {
			if !contact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(contact.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(contact.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(contact.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(contact.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(contact.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.AccountTable,
			Columns: []string{contact.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.AccountTable,
			Columns: []string{contact.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Contact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
