// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/message"
	"github.com/arqueon/dankmail/core/ent/thread"
	"github.com/arqueon/dankmail/core/internal/provider"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderMessageID sets the "provider_message_id" field.
func (_c *MessageCreate) SetProviderMessageID(v string) *MessageCreate {
	_c.mutation.SetProviderMessageID(v)
	return _c
}

// SetRfc822MessageID sets the "rfc822_message_id" field.
func (_c *MessageCreate) SetRfc822MessageID(v string) *MessageCreate {
	_c.mutation.SetRfc822MessageID(v)
	return _c
}

// SetNillableRfc822MessageID sets the "rfc822_message_id" field if the given value is not nil.
func (_c *MessageCreate) SetNillableRfc822MessageID(v *string) *MessageCreate {
	if v != nil {
		_c.SetRfc822MessageID(*v)
	}
	return _c
}

// SetFrom sets the "from" field.
func (_c *MessageCreate) SetFrom(v string) *MessageCreate {
	_c.mutation.SetFrom(v)
	return _c
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_c *MessageCreate) SetNillableFrom(v *string) *MessageCreate {
	if v != nil {
		_c.SetFrom(*v)
	}
	return _c
}

// SetTo sets the "to" field.
func (_c *MessageCreate) SetTo(v []string) *MessageCreate {
	_c.mutation.SetTo(v)
	return _c
}

// SetCc sets the "cc" field.
func (_c *MessageCreate) SetCc(v []string) *MessageCreate {
	_c.mutation.SetCc(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *MessageCreate) SetDate(v time.Time) *MessageCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetSnippet sets the "snippet" field.
func (_c *MessageCreate) SetSnippet(v string) *MessageCreate {
	_c.mutation.SetSnippet(v)
	return _c
}

// SetNillableSnippet sets the "snippet" field if the given value is not nil.
func (_c *MessageCreate) SetNillableSnippet(v *string) *MessageCreate {
	if v != nil {
		_c.SetSnippet(*v)
	}
	return _c
}

// SetBodyText sets the "body_text" field.
func (_c *MessageCreate) SetBodyText(v string) *MessageCreate {
	_c.mutation.SetBodyText(v)
	return _c
}

// SetNillableBodyText sets the "body_text" field if the given value is not nil.
func (_c *MessageCreate) SetNillableBodyText(v *string) *MessageCreate {
	if v != nil {
		_c.SetBodyText(*v)
	}
	return _c
}

// SetReplyHeaders sets the "reply_headers" field.
func (_c *MessageCreate) SetReplyHeaders(v map[string]string) *MessageCreate {
	_c.mutation.SetReplyHeaders(v)
	return _c
}

// SetAttachments sets the "attachments" field.
func (_c *MessageCreate) SetAttachments(v []provider.AttachmentMeta) *MessageCreate {
	_c.mutation.SetAttachments(v)
	return _c
}

// SetThreadID sets the "thread" edge to the Thread entity by ID.
func (_c *MessageCreate) SetThreadID(id int) *MessageCreate {
	_c.mutation.SetThreadID(id)
	return _c
}

// SetThread sets the "thread" edge to the Thread entity.
func (_c *MessageCreate) SetThread(v *Thread) *MessageCreate {
	return _c.SetThreadID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_c *MessageCreate) Mutation() *MessageMutation {
	return _c.mutation
}

// Save creates the Message in the database.
func (_c *MessageCreate) Save(ctx context.Context) (*Message, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageCreate) defaults() {
	if _, ok := _c.mutation.Rfc822MessageID(); !ok {
		v := message.DefaultRfc822MessageID
		_c.mutation.SetRfc822MessageID(v)
	}
	if _, ok := _c.mutation.From(); !ok {
		v := message.DefaultFrom
		_c.mutation.SetFrom(v)
	}
	if _, ok := _c.mutation.To(); !ok {
		v := message.DefaultTo
		_c.mutation.SetTo(v)
	}
	if _, ok := _c.mutation.Cc(); !ok {
		v := message.DefaultCc
		_c.mutation.SetCc(v)
	}
	if _, ok := _c.mutation.Snippet(); !ok {
		v := message.DefaultSnippet
		_c.mutation.SetSnippet(v)
	}
	if _, ok := _c.mutation.BodyText(); !ok {
		v := message.DefaultBodyText
		_c.mutation.SetBodyText(v)
	}
	if _, ok := _c.mutation.ReplyHeaders(); !ok {
		v := message.DefaultReplyHeaders
		_c.mutation.SetReplyHeaders(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageCreate) check() error {
	if _, ok := _c.mutation.ProviderMessageID(); !ok {
		return &ValidationError{Name: "provider_message_id", err: errors.New(`ent: missing required field "Message.provider_message_id"`)}
	}
	if _, ok := _c.mutation.Rfc822MessageID(); !ok {
		return &ValidationError{Name: "rfc822_message_id", err: errors.New(`ent: missing required field "Message.rfc822_message_id"`)}
	}
	if _, ok := _c.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "Message.from"`)}
	}
	if _, ok := _c.mutation.To(); !ok {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required field "Message.to"`)}
	}
	if _, ok := _c.mutation.Cc(); !ok {
		return &ValidationError{Name: "cc", err: errors.New(`ent: missing required field "Message.cc"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Message.date"`)}
	}
	if _, ok := _c.mutation.Snippet(); !ok {
		return &ValidationError{Name: "snippet", err: errors.New(`ent: missing required field "Message.snippet"`)}
	}
	if _, ok := _c.mutation.BodyText(); !ok {
		return &ValidationError{Name: "body_text", err: errors.New(`ent: missing required field "Message.body_text"`)}
	}
	if _, ok := _c.mutation.ReplyHeaders(); !ok {
		return &ValidationError{Name: "reply_headers", err: errors.New(`ent: missing required field "Message.reply_headers"`)}
	}
	if len(_c.mutation.ThreadIDs()) == 0 {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "Message.thread"`)}
	}
	return nil
}

func (_c *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderMessageID(); ok {
		_spec.SetField(message.FieldProviderMessageID, field.TypeString, value)
		_node.ProviderMessageID = value
	}
	if value, ok := _c.mutation.Rfc822MessageID(); ok {
		_spec.SetField(message.FieldRfc822MessageID, field.TypeString, value)
		_node.Rfc822MessageID = value
	}
	if value, ok := _c.mutation.From(); ok {
		_spec.SetField(message.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := _c.mutation.To(); ok {
		_spec.SetField(message.FieldTo, field.TypeJSON, value)
		_node.To = value
	}
	if value, ok := _c.mutation.Cc(); ok {
		_spec.SetField(message.FieldCc, field.TypeJSON, value)
		_node.Cc = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(message.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Snippet(); ok {
		_spec.SetField(message.FieldSnippet, field.TypeString, value)
		_node.Snippet = value
	}
	if value, ok := _c.mutation.BodyText(); ok {
		_spec.SetField(message.FieldBodyText, field.TypeString, value)
		_node.BodyText = value
	}
	if value, ok := _c.mutation.ReplyHeaders(); ok {
		_spec.SetField(message.FieldReplyHeaders, field.TypeJSON, value)
		_node.ReplyHeaders = value
	}
	if value, ok := _c.mutation.Attachments(); ok {
		_spec.SetField(message.FieldAttachments, field.TypeJSON, value)
		_node.Attachments = value
	}
	if nodes := _c.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ThreadTable,
			Columns: []string{message.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.thread_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.Create().
//		SetProviderMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetProviderMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageCreate) OnConflict(opts ...sql.ConflictOption) *MessageUpsertOne {
	_c.conflict = opts
	return &MessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageCreate) OnConflictColumns(columns ...string) *MessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertOne{
		create: _c,
	}
}

type (
	// MessageUpsertOne is the builder for "upsert"-ing
	//  one Message node.
	MessageUpsertOne struct {
		create *MessageCreate
	}

	// MessageUpsert is the "OnConflict" setter.
	MessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderMessageID sets the "provider_message_id" field.
func (u *MessageUpsert) SetProviderMessageID(v string) *MessageUpsert {
	u.Set(message.FieldProviderMessageID, v)
	return u
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateProviderMessageID() *MessageUpsert {
	u.SetExcluded(message.FieldProviderMessageID)
	return u
}

// SetRfc822MessageID sets the "rfc822_message_id" field.
func (u *MessageUpsert) SetRfc822MessageID(v string) *MessageUpsert {
	u.Set(message.FieldRfc822MessageID, v)
	return u
}

// UpdateRfc822MessageID sets the "rfc822_message_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateRfc822MessageID() *MessageUpsert {
	u.SetExcluded(message.FieldRfc822MessageID)
	return u
}

// SetFrom sets the "from" field.
func (u *MessageUpsert) SetFrom(v string) *MessageUpsert {
	u.Set(message.FieldFrom, v)
	return u
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *MessageUpsert) UpdateFrom() *MessageUpsert {
	u.SetExcluded(message.FieldFrom)
	return u
}

// SetTo sets the "to" field.
func (u *MessageUpsert) SetTo(v []string) *MessageUpsert {
	u.Set(message.FieldTo, v)
	return u
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *MessageUpsert) UpdateTo() *MessageUpsert {
	u.SetExcluded(message.FieldTo)
	return u
}

// SetCc sets the "cc" field.
func (u *MessageUpsert) SetCc(v []string) *MessageUpsert {
	u.Set(message.FieldCc, v)
	return u
}

// UpdateCc sets the "cc" field to the value that was provided on create.
func (u *MessageUpsert) UpdateCc() *MessageUpsert {
	u.SetExcluded(message.FieldCc)
	return u
}

// SetDate sets the "date" field.
func (u *MessageUpsert) SetDate(v time.Time) *MessageUpsert {
	u.Set(message.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *MessageUpsert) UpdateDate() *MessageUpsert {
	u.SetExcluded(message.FieldDate)
	return u
}

// SetSnippet sets the "snippet" field.
func (u *MessageUpsert) SetSnippet(v string) *MessageUpsert {
	u.Set(message.FieldSnippet, v)
	return u
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *MessageUpsert) UpdateSnippet() *MessageUpsert {
	u.SetExcluded(message.FieldSnippet)
	return u
}

// SetBodyText sets the "body_text" field.
func (u *MessageUpsert) SetBodyText(v string) *MessageUpsert {
	u.Set(message.FieldBodyText, v)
	return u
}

// UpdateBodyText sets the "body_text" field to the value that was provided on create.
func (u *MessageUpsert) UpdateBodyText() *MessageUpsert {
	u.SetExcluded(message.FieldBodyText)
	return u
}

// SetReplyHeaders sets the "reply_headers" field.
func (u *MessageUpsert) SetReplyHeaders(v map[string]string) *MessageUpsert {
	u.Set(message.FieldReplyHeaders, v)
	return u
}

// UpdateReplyHeaders sets the "reply_headers" field to the value that was provided on create.
func (u *MessageUpsert) UpdateReplyHeaders() *MessageUpsert {
	u.SetExcluded(message.FieldReplyHeaders)
	return u
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsert) SetAttachments(v []provider.AttachmentMeta) *MessageUpsert {
	u.Set(message.FieldAttachments, v)
	return u
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsert) UpdateAttachments() *MessageUpsert {
	u.SetExcluded(message.FieldAttachments)
	return u
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsert) ClearAttachments() *MessageUpsert {
	u.SetNull(message.FieldAttachments)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageUpsertOne) UpdateNewValues() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MessageUpsertOne) Ignore() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertOne) DoNothing() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreate.OnConflict
// documentation for more info.
func (u *MessageUpsertOne) Update(set func(*MessageUpsert)) *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderMessageID sets the "provider_message_id" field.
func (u *MessageUpsertOne) SetProviderMessageID(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetProviderMessageID(v)
	})
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateProviderMessageID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateProviderMessageID()
	})
}

// SetRfc822MessageID sets the "rfc822_message_id" field.
func (u *MessageUpsertOne) SetRfc822MessageID(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetRfc822MessageID(v)
	})
}

// UpdateRfc822MessageID sets the "rfc822_message_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateRfc822MessageID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateRfc822MessageID()
	})
}

// SetFrom sets the "from" field.
func (u *MessageUpsertOne) SetFrom(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateFrom() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateFrom()
	})
}

// SetTo sets the "to" field.
func (u *MessageUpsertOne) SetTo(v []string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetTo(v)
	})
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateTo() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateTo()
	})
}

// SetCc sets the "cc" field.
func (u *MessageUpsertOne) SetCc(v []string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetCc(v)
	})
}

// UpdateCc sets the "cc" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateCc() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateCc()
	})
}

// SetDate sets the "date" field.
func (u *MessageUpsertOne) SetDate(v time.Time) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateDate() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateDate()
	})
}

// SetSnippet sets the "snippet" field.
func (u *MessageUpsertOne) SetSnippet(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetSnippet(v)
	})
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateSnippet() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSnippet()
	})
}

// SetBodyText sets the "body_text" field.
func (u *MessageUpsertOne) SetBodyText(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetBodyText(v)
	})
}

// UpdateBodyText sets the "body_text" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateBodyText() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateBodyText()
	})
}

// SetReplyHeaders sets the "reply_headers" field.
func (u *MessageUpsertOne) SetReplyHeaders(v map[string]string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetReplyHeaders(v)
	})
}

// UpdateReplyHeaders sets the "reply_headers" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateReplyHeaders() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateReplyHeaders()
	})
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsertOne) SetAttachments(v []provider.AttachmentMeta) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetAttachments(v)
	})
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateAttachments() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateAttachments()
	})
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsertOne) ClearAttachments() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearAttachments()
	})
}

// Exec executes the query.
func (u *MessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
	conflict []sql.ConflictOption
}

// Save creates the Message entities in the database.
func (_c *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Message, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetProviderMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageUpsertBulk {
	_c.conflict = opts
	return &MessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageCreateBulk) OnConflictColumns(columns ...string) *MessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertBulk{
		create: _c,
	}
}

// MessageUpsertBulk is the builder for "upsert"-ing
// a bulk of Message nodes.
type MessageUpsertBulk struct {
	create *MessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageUpsertBulk) UpdateNewValues() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MessageUpsertBulk) Ignore() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertBulk) DoNothing() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreateBulk.OnConflict
// documentation for more info.
func (u *MessageUpsertBulk) Update(set func(*MessageUpsert)) *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderMessageID sets the "provider_message_id" field.
func (u *MessageUpsertBulk) SetProviderMessageID(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetProviderMessageID(v)
	})
}

// UpdateProviderMessageID sets the "provider_message_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateProviderMessageID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateProviderMessageID()
	})
}

// SetRfc822MessageID sets the "rfc822_message_id" field.
func (u *MessageUpsertBulk) SetRfc822MessageID(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetRfc822MessageID(v)
	})
}

// UpdateRfc822MessageID sets the "rfc822_message_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateRfc822MessageID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateRfc822MessageID()
	})
}

// SetFrom sets the "from" field.
func (u *MessageUpsertBulk) SetFrom(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateFrom() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateFrom()
	})
}

// SetTo sets the "to" field.
func (u *MessageUpsertBulk) SetTo(v []string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetTo(v)
	})
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateTo() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateTo()
	})
}

// SetCc sets the "cc" field.
func (u *MessageUpsertBulk) SetCc(v []string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetCc(v)
	})
}

// UpdateCc sets the "cc" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateCc() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateCc()
	})
}

// SetDate sets the "date" field.
func (u *MessageUpsertBulk) SetDate(v time.Time) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateDate() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateDate()
	})
}

// SetSnippet sets the "snippet" field.
func (u *MessageUpsertBulk) SetSnippet(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetSnippet(v)
	})
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateSnippet() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateSnippet()
	})
}

// SetBodyText sets the "body_text" field.
func (u *MessageUpsertBulk) SetBodyText(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetBodyText(v)
	})
}

// UpdateBodyText sets the "body_text" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateBodyText() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateBodyText()
	})
}

// SetReplyHeaders sets the "reply_headers" field.
func (u *MessageUpsertBulk) SetReplyHeaders(v map[string]string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetReplyHeaders(v)
	})
}

// UpdateReplyHeaders sets the "reply_headers" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateReplyHeaders() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateReplyHeaders()
	})
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsertBulk) SetAttachments(v []provider.AttachmentMeta) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetAttachments(v)
	})
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateAttachments() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateAttachments()
	})
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsertBulk) ClearAttachments() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearAttachments()
	})
}

// Exec executes the query.
func (u *MessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
