// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/notifyrule"
	"github.com/arqueon/dankmail/core/ent/predicate"
	"github.com/google/uuid"
)

// NotifyRuleUpdate is the builder for updating NotifyRule entities.
type NotifyRuleUpdate struct {
	config
	hooks     []Hook
	mutation  *NotifyRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotifyRuleUpdate builder.
func (_u *NotifyRuleUpdate) Where(ps ...predicate.NotifyRule) *NotifyRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *NotifyRuleUpdate) SetLabel(v string) *NotifyRuleUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *NotifyRuleUpdate) SetNillableLabel(v *string) *NotifyRuleUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyRuleUpdate) SetEnabled(v bool) *NotifyRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyRuleUpdate) SetNillableEnabled(v *bool) *NotifyRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotify sets the "notify" field.
func (_u *NotifyRuleUpdate) SetNotify(v bool) *NotifyRuleUpdate {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *NotifyRuleUpdate) SetNillableNotify(v *bool) *NotifyRuleUpdate {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetSound sets the "sound" field.
func (_u *NotifyRuleUpdate) SetSound(v string) *NotifyRuleUpdate {
	_u.mutation.SetSound(v)
	return _u
}

// SetNillableSound sets the "sound" field if the given value is not nil.
func (_u *NotifyRuleUpdate) SetNillableSound(v *string) *NotifyRuleUpdate {
	if v != nil {
		_u.SetSound(*v)
	}
	return _u
}

// SetUrgency sets the "urgency" field.
func (_u *NotifyRuleUpdate) SetUrgency(v notifyrule.Urgency) *NotifyRuleUpdate {
	_u.mutation.SetUrgency(v)
	return _u
}

// SetNillableUrgency sets the "urgency" field if the given value is not nil.
func (_u *NotifyRuleUpdate) SetNillableUrgency(v *notifyrule.Urgency) *NotifyRuleUpdate {
	if v != nil {
		_u.SetUrgency(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *NotifyRuleUpdate) SetAccountID(id uuid.UUID) *NotifyRuleUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *NotifyRuleUpdate) SetAccount(v *Account) *NotifyRuleUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the NotifyRuleMutation object of the builder.
func (_u *NotifyRuleUpdate) Mutation() *NotifyRuleMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *NotifyRuleUpdate) ClearAccount() *NotifyRuleUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifyRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifyRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyRuleUpdate) check() error {
	if v, ok := _u.mutation.Urgency(); ok {
		if err := notifyrule.UrgencyValidator(v); err != nil {
			return &ValidationError{Name: "urgency", err: fmt.Errorf(`ent: validator failed for field "NotifyRule.urgency": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotifyRule.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotifyRuleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotifyRuleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotifyRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifyrule.Table, notifyrule.Columns, sqlgraph.NewFieldSpec(notifyrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(notifyrule.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifyrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(notifyrule.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sound(); ok {
		_spec.SetField(notifyrule.FieldSound, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgency(); ok {
		_spec.SetField(notifyrule.FieldUrgency, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifyrule.AccountTable,
			Columns: []string{notifyrule.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifyrule.AccountTable,
			Columns: []string{notifyrule.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifyrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifyRuleUpdateOne is the builder for updating a single NotifyRule entity.
type NotifyRuleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotifyRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetLabel sets the "label" field.
func (_u *NotifyRuleUpdateOne) SetLabel(v string) *NotifyRuleUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *NotifyRuleUpdateOne) SetNillableLabel(v *string) *NotifyRuleUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyRuleUpdateOne) SetEnabled(v bool) *NotifyRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyRuleUpdateOne) SetNillableEnabled(v *bool) *NotifyRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotify sets the "notify" field.
func (_u *NotifyRuleUpdateOne) SetNotify(v bool) *NotifyRuleUpdateOne {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *NotifyRuleUpdateOne) SetNillableNotify(v *bool) *NotifyRuleUpdateOne {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetSound sets the "sound" field.
func (_u *NotifyRuleUpdateOne) SetSound(v string) *NotifyRuleUpdateOne {
	_u.mutation.SetSound(v)
	return _u
}

// SetNillableSound sets the "sound" field if the given value is not nil.
func (_u *NotifyRuleUpdateOne) SetNillableSound(v *string) *NotifyRuleUpdateOne {
	if v != nil {
		_u.SetSound(*v)
	}
	return _u
}

// SetUrgency sets the "urgency" field.
func (_u *NotifyRuleUpdateOne) SetUrgency(v notifyrule.Urgency) *NotifyRuleUpdateOne {
	_u.mutation.SetUrgency(v)
	return _u
}

// SetNillableUrgency sets the "urgency" field if the given value is not nil.
func (_u *NotifyRuleUpdateOne) SetNillableUrgency(v *notifyrule.Urgency) *NotifyRuleUpdateOne {
	if v != nil {
		_u.SetUrgency(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *NotifyRuleUpdateOne) SetAccountID(id uuid.UUID) *NotifyRuleUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *NotifyRuleUpdateOne) SetAccount(v *Account) *NotifyRuleUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the NotifyRuleMutation object of the builder.
func (_u *NotifyRuleUpdateOne) Mutation() *NotifyRuleMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *NotifyRuleUpdateOne) ClearAccount() *NotifyRuleUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the NotifyRuleUpdate builder.
func (_u *NotifyRuleUpdateOne) Where(ps ...predicate.NotifyRule) *NotifyRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifyRuleUpdateOne) Select(field string, fields ...string) *NotifyRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifyRule entity.
func (_u *NotifyRuleUpdateOne) Save(ctx context.Context) (*NotifyRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyRuleUpdateOne) SaveX(ctx context.Context) *NotifyRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifyRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Urgency(); ok {
		if err := notifyrule.UrgencyValidator(v); err != nil {
			return &ValidationError{Name: "urgency", err: fmt.Errorf(`ent: validator failed for field "NotifyRule.urgency": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotifyRule.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotifyRuleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotifyRuleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotifyRuleUpdateOne) sqlSave(ctx context.Context) (_node *NotifyRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifyrule.Table, notifyrule.Columns, sqlgraph.NewFieldSpec(notifyrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotifyRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifyrule.FieldID)
		for _, f := range fields {
			if !notifyrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notifyrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(notifyrule.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifyrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(notifyrule.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sound(); ok {
		_spec.SetField(notifyrule.FieldSound, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgency(); ok {
		_spec.SetField(notifyrule.FieldUrgency, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifyrule.AccountTable,
			Columns: []string{notifyrule.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifyrule.AccountTable,
			Columns: []string{notifyrule.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotifyRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifyrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
