// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/notifyrule"
	"github.com/google/uuid"
)

// NotifyRuleCreate is the builder for creating a NotifyRule entity.
type NotifyRuleCreate struct {
	config
	mutation *NotifyRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLabel sets the "label" field.
func (_c *NotifyRuleCreate) SetLabel(v string) *NotifyRuleCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotifyRuleCreate) SetEnabled(v bool) *NotifyRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotifyRuleCreate) SetNillableEnabled(v *bool) *NotifyRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetNotify sets the "notify" field.
func (_c *NotifyRuleCreate) SetNotify(v bool) *NotifyRuleCreate {
	_c.mutation.SetNotify(v)
	return _c
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_c *NotifyRuleCreate) SetNillableNotify(v *bool) *NotifyRuleCreate {
	if v != nil {
		_c.SetNotify(*v)
	}
	return _c
}

// SetSound sets the "sound" field.
func (_c *NotifyRuleCreate) SetSound(v string) *NotifyRuleCreate {
	_c.mutation.SetSound(v)
	return _c
}

// SetNillableSound sets the "sound" field if the given value is not nil.
func (_c *NotifyRuleCreate) SetNillableSound(v *string) *NotifyRuleCreate {
	if v != nil {
		_c.SetSound(*v)
	}
	return _c
}

// SetUrgency sets the "urgency" field.
func (_c *NotifyRuleCreate) SetUrgency(v notifyrule.Urgency) *NotifyRuleCreate {
	_c.mutation.SetUrgency(v)
	return _c
}

// SetNillableUrgency sets the "urgency" field if the given value is not nil.
func (_c *NotifyRuleCreate) SetNillableUrgency(v *notifyrule.Urgency) *NotifyRuleCreate {
	if v != nil {
		_c.SetUrgency(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *NotifyRuleCreate) SetAccountID(id uuid.UUID) *NotifyRuleCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *NotifyRuleCreate) SetAccount(v *Account) *NotifyRuleCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the NotifyRuleMutation object of the builder.
func (_c *NotifyRuleCreate) Mutation() *NotifyRuleMutation {
	return _c.mutation
}

// Save creates the NotifyRule in the database.
func (_c *NotifyRuleCreate) Save(ctx context.Context) (*NotifyRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotifyRuleCreate) SaveX(ctx context.Context) *NotifyRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotifyRuleCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notifyrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Notify(); !ok {
		v := notifyrule.DefaultNotify
		_c.mutation.SetNotify(v)
	}
	if _, ok := _c.mutation.Sound(); !ok {
		v := notifyrule.DefaultSound
		_c.mutation.SetSound(v)
	}
	if _, ok := _c.mutation.Urgency(); !ok {
		v := notifyrule.DefaultUrgency
		_c.mutation.SetUrgency(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotifyRuleCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "NotifyRule.label"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotifyRule.enabled"`)}
	}
	if _, ok := _c.mutation.Notify(); !ok {
		return &ValidationError{Name: "notify", err: errors.New(`ent: missing required field "NotifyRule.notify"`)}
	}
	if _, ok := _c.mutation.Sound(); !ok {
		return &ValidationError{Name: "sound", err: errors.New(`ent: missing required field "NotifyRule.sound"`)}
	}
	if _, ok := _c.mutation.Urgency(); !ok {
		return &ValidationError{Name: "urgency", err: errors.New(`ent: missing required field "NotifyRule.urgency"`)}
	}
	if v, ok := _c.mutation.Urgency(); ok {
		if err := notifyrule.UrgencyValidator(v); err != nil {
			return &ValidationError{Name: "urgency", err: fmt.Errorf(`ent: validator failed for field "NotifyRule.urgency": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "NotifyRule.account"`)}
	}
	return nil
}

func (_c *NotifyRuleCreate) sqlSave(ctx context.Context) (*NotifyRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotifyRuleCreate) createSpec() (*NotifyRule, *sqlgraph.CreateSpec) {
	var (
		_node = &NotifyRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notifyrule.Table, sqlgraph.NewFieldSpec(notifyrule.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(notifyrule.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notifyrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Notify(); ok {
		_spec.SetField(notifyrule.FieldNotify, field.TypeBool, value)
		_node.Notify = value
	}
	if value, ok := _c.mutation.Sound(); ok {
		_spec.SetField(notifyrule.FieldSound, field.TypeString, value)
		_node.Sound = value
	}
	if value, ok := _c.mutation.Urgency(); ok {
		_spec.SetField(notifyrule.FieldUrgency, field.TypeEnum, value)
		_node.Urgency = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifyrule.AccountTable,
			Columns: []string{notifyrule.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_notify_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotifyRule.Create().
//		SetLabel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotifyRuleUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *NotifyRuleCreate) OnConflict(opts ...sql.ConflictOption) *NotifyRuleUpsertOne {
	_c.conflict = opts
	return &NotifyRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotifyRuleCreate) OnConflictColumns(columns ...string) *NotifyRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotifyRuleUpsertOne{
		create: _c,
	}
}

type (
	// NotifyRuleUpsertOne is the builder for "upsert"-ing
	//  one NotifyRule node.
	NotifyRuleUpsertOne struct {
		create *NotifyRuleCreate
	}

	// NotifyRuleUpsert is the "OnConflict" setter.
	NotifyRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetLabel sets the "label" field.
func (u *NotifyRuleUpsert) SetLabel(v string) *NotifyRuleUpsert {
	u.Set(notifyrule.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *NotifyRuleUpsert) UpdateLabel() *NotifyRuleUpsert {
	u.SetExcluded(notifyrule.FieldLabel)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *NotifyRuleUpsert) SetEnabled(v bool) *NotifyRuleUpsert {
	u.Set(notifyrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyRuleUpsert) UpdateEnabled() *NotifyRuleUpsert {
	u.SetExcluded(notifyrule.FieldEnabled)
	return u
}

// SetNotify sets the "notify" field.
func (u *NotifyRuleUpsert) SetNotify(v bool) *NotifyRuleUpsert {
	u.Set(notifyrule.FieldNotify, v)
	return u
}

// UpdateNotify sets the "notify" field to the value that was provided on create.
func (u *NotifyRuleUpsert) UpdateNotify() *NotifyRuleUpsert {
	u.SetExcluded(notifyrule.FieldNotify)
	return u
}

// SetSound sets the "sound" field.
func (u *NotifyRuleUpsert) SetSound(v string) *NotifyRuleUpsert {
	u.Set(notifyrule.FieldSound, v)
	return u
}

// UpdateSound sets the "sound" field to the value that was provided on create.
func (u *NotifyRuleUpsert) UpdateSound() *NotifyRuleUpsert {
	u.SetExcluded(notifyrule.FieldSound)
	return u
}

// SetUrgency sets the "urgency" field.
func (u *NotifyRuleUpsert) SetUrgency(v notifyrule.Urgency) *NotifyRuleUpsert {
	u.Set(notifyrule.FieldUrgency, v)
	return u
}

// UpdateUrgency sets the "urgency" field to the value that was provided on create.
func (u *NotifyRuleUpsert) UpdateUrgency() *NotifyRuleUpsert {
	u.SetExcluded(notifyrule.FieldUrgency)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotifyRuleUpsertOne) UpdateNewValues() *NotifyRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotifyRuleUpsertOne) Ignore() *NotifyRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotifyRuleUpsertOne) DoNothing() *NotifyRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotifyRuleCreate.OnConflict
// documentation for more info.
func (u *NotifyRuleUpsertOne) Update(set func(*NotifyRuleUpsert)) *NotifyRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotifyRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *NotifyRuleUpsertOne) SetLabel(v string) *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *NotifyRuleUpsertOne) UpdateLabel() *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateLabel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotifyRuleUpsertOne) SetEnabled(v bool) *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyRuleUpsertOne) UpdateEnabled() *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotify sets the "notify" field.
func (u *NotifyRuleUpsertOne) SetNotify(v bool) *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetNotify(v)
	})
}

// UpdateNotify sets the "notify" field to the value that was provided on create.
func (u *NotifyRuleUpsertOne) UpdateNotify() *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateNotify()
	})
}

// SetSound sets the "sound" field.
func (u *NotifyRuleUpsertOne) SetSound(v string) *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetSound(v)
	})
}

// UpdateSound sets the "sound" field to the value that was provided on create.
func (u *NotifyRuleUpsertOne) UpdateSound() *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateSound()
	})
}

// SetUrgency sets the "urgency" field.
func (u *NotifyRuleUpsertOne) SetUrgency(v notifyrule.Urgency) *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetUrgency(v)
	})
}

// UpdateUrgency sets the "urgency" field to the value that was provided on create.
func (u *NotifyRuleUpsertOne) UpdateUrgency() *NotifyRuleUpsertOne {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateUrgency()
	})
}

// Exec executes the query.
func (u *NotifyRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotifyRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotifyRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotifyRuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotifyRuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotifyRuleCreateBulk is the builder for creating many NotifyRule entities in bulk.
type NotifyRuleCreateBulk struct {
	config
	err      error
	builders []*NotifyRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the NotifyRule entities in the database.
func (_c *NotifyRuleCreateBulk) Save(ctx context.Context) ([]*NotifyRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotifyRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotifyRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotifyRuleCreateBulk) SaveX(ctx context.Context) []*NotifyRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotifyRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotifyRuleUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *NotifyRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotifyRuleUpsertBulk {
	_c.conflict = opts
	return &NotifyRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotifyRuleCreateBulk) OnConflictColumns(columns ...string) *NotifyRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotifyRuleUpsertBulk{
		create: _c,
	}
}

// NotifyRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of NotifyRule nodes.
type NotifyRuleUpsertBulk struct {
	create *NotifyRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotifyRuleUpsertBulk) UpdateNewValues() *NotifyRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotifyRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotifyRuleUpsertBulk) Ignore() *NotifyRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotifyRuleUpsertBulk) DoNothing() *NotifyRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotifyRuleCreateBulk.OnConflict
// documentation for more info.
func (u *NotifyRuleUpsertBulk) Update(set func(*NotifyRuleUpsert)) *NotifyRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotifyRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *NotifyRuleUpsertBulk) SetLabel(v string) *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *NotifyRuleUpsertBulk) UpdateLabel() *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateLabel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotifyRuleUpsertBulk) SetEnabled(v bool) *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyRuleUpsertBulk) UpdateEnabled() *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotify sets the "notify" field.
func (u *NotifyRuleUpsertBulk) SetNotify(v bool) *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetNotify(v)
	})
}

// UpdateNotify sets the "notify" field to the value that was provided on create.
func (u *NotifyRuleUpsertBulk) UpdateNotify() *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateNotify()
	})
}

// SetSound sets the "sound" field.
func (u *NotifyRuleUpsertBulk) SetSound(v string) *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetSound(v)
	})
}

// UpdateSound sets the "sound" field to the value that was provided on create.
func (u *NotifyRuleUpsertBulk) UpdateSound() *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateSound()
	})
}

// SetUrgency sets the "urgency" field.
func (u *NotifyRuleUpsertBulk) SetUrgency(v notifyrule.Urgency) *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.SetUrgency(v)
	})
}

// UpdateUrgency sets the "urgency" field to the value that was provided on create.
func (u *NotifyRuleUpsertBulk) UpdateUrgency() *NotifyRuleUpsertBulk {
	return u.Update(func(s *NotifyRuleUpsert) {
		s.UpdateUrgency()
	})
}

// Exec executes the query.
func (u *NotifyRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotifyRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotifyRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotifyRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
