// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/pendingop"
	"github.com/google/uuid"
)

// PendingOp is the model entity for the PendingOp schema.
type PendingOp struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProviderThreadIds holds the value of the "provider_thread_ids" field.
	ProviderThreadIds []string `json:"provider_thread_ids,omitempty"`
	// OpType holds the value of the "op_type" field.
	OpType pendingop.OpType `json:"op_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// State holds the value of the "state" field.
	State pendingop.State `json:"state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PendingOpQuery when eager-loading is set.
	Edges               PendingOpEdges `json:"edges"`
	account_pending_ops *uuid.UUID
	selectValues        sql.SelectValues
}

// PendingOpEdges holds the relations/edges for other nodes in the graph.
type PendingOpEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PendingOpEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PendingOp) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pendingop.FieldProviderThreadIds, pendingop.FieldPayload:
			values[i] = new([]byte)
		case pendingop.FieldID, pendingop.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case pendingop.FieldOpType, pendingop.FieldLastError, pendingop.FieldState:
			values[i] = new(sql.NullString)
		case pendingop.FieldCreatedAt, pendingop.FieldNextAttemptAt:
			values[i] = new(sql.NullTime)
		case pendingop.ForeignKeys[0]: // account_pending_ops
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PendingOp fields.
func (_m *PendingOp) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pendingop.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pendingop.FieldProviderThreadIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_thread_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderThreadIds); err != nil {
					return fmt.Errorf("unmarshal field provider_thread_ids: %w", err)
				}
			}
		case pendingop.FieldOpType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field op_type", values[i])
			} else if value.Valid {
				_m.OpType = pendingop.OpType(value.String)
			}
		case pendingop.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case pendingop.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pendingop.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case pendingop.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = new(time.Time)
				*_m.NextAttemptAt = value.Time
			}
		case pendingop.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case pendingop.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = pendingop.State(value.String)
			}
		case pendingop.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field account_pending_ops", values[i])
			} else if value.Valid {
				_m.account_pending_ops = new(uuid.UUID)
				*_m.account_pending_ops = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PendingOp.
// This includes values selected through modifiers, order, etc.
func (_m *PendingOp) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the PendingOp entity.
func (_m *PendingOp) QueryAccount() *AccountQuery {
	return NewPendingOpClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this PendingOp.
// Note that you need to call PendingOp.Unwrap() before calling this method if this PendingOp
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PendingOp) Update() *PendingOpUpdateOne {
	return NewPendingOpClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PendingOp entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PendingOp) Unwrap() *PendingOp {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PendingOp is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PendingOp) String() string {
	var builder strings.Builder
	builder.WriteString("PendingOp(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_thread_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderThreadIds))
	builder.WriteString(", ")
	builder.WriteString("op_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpType))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.NextAttemptAt; v != nil {
		builder.WriteString("next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteByte(')')
	return builder.String()
}

// PendingOps is a parsable slice of PendingOp.
type PendingOps []*PendingOp
