// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/pendingop"
	"github.com/google/uuid"
)

// PendingOpCreate is the builder for creating a PendingOp entity.
type PendingOpCreate struct {
	config
	mutation *PendingOpMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (_c *PendingOpCreate) SetProviderThreadIds(v []string) *PendingOpCreate {
	_c.mutation.SetProviderThreadIds(v)
	return _c
}

// SetOpType sets the "op_type" field.
func (_c *PendingOpCreate) SetOpType(v pendingop.OpType) *PendingOpCreate {
	_c.mutation.SetOpType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *PendingOpCreate) SetPayload(v map[string]interface{}) *PendingOpCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PendingOpCreate) SetCreatedAt(v time.Time) *PendingOpCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PendingOpCreate) SetNillableCreatedAt(v *time.Time) *PendingOpCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *PendingOpCreate) SetAttempts(v int) *PendingOpCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *PendingOpCreate) SetNillableAttempts(v *int) *PendingOpCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *PendingOpCreate) SetNextAttemptAt(v time.Time) *PendingOpCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *PendingOpCreate) SetNillableNextAttemptAt(v *time.Time) *PendingOpCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *PendingOpCreate) SetLastError(v string) *PendingOpCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *PendingOpCreate) SetNillableLastError(v *string) *PendingOpCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *PendingOpCreate) SetState(v pendingop.State) *PendingOpCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *PendingOpCreate) SetNillableState(v *pendingop.State) *PendingOpCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *PendingOpCreate) SetAccountID(id uuid.UUID) *PendingOpCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *PendingOpCreate) SetAccount(v *Account) *PendingOpCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the PendingOpMutation object of the builder.
func (_c *PendingOpCreate) Mutation() *PendingOpMutation {
	return _c.mutation
}

// Save creates the PendingOp in the database.
func (_c *PendingOpCreate) Save(ctx context.Context) (*PendingOp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PendingOpCreate) SaveX(ctx context.Context) *PendingOp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PendingOpCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PendingOpCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PendingOpCreate) defaults() {
	if _, ok := _c.mutation.ProviderThreadIds(); !ok {
		v := pendingop.DefaultProviderThreadIds
		_c.mutation.SetProviderThreadIds(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := pendingop.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pendingop.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := pendingop.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := pendingop.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := pendingop.DefaultState
		_c.mutation.SetState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PendingOpCreate) check() error {
	if _, ok := _c.mutation.ProviderThreadIds(); !ok {
		return &ValidationError{Name: "provider_thread_ids", err: errors.New(`ent: missing required field "PendingOp.provider_thread_ids"`)}
	}
	if _, ok := _c.mutation.OpType(); !ok {
		return &ValidationError{Name: "op_type", err: errors.New(`ent: missing required field "PendingOp.op_type"`)}
	}
	if v, ok := _c.mutation.OpType(); ok {
		if err := pendingop.OpTypeValidator(v); err != nil {
			return &ValidationError{Name: "op_type", err: fmt.Errorf(`ent: validator failed for field "PendingOp.op_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "PendingOp.payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PendingOp.created_at"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "PendingOp.attempts"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "PendingOp.last_error"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "PendingOp.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := pendingop.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PendingOp.state": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "PendingOp.account"`)}
	}
	return nil
}

func (_c *PendingOpCreate) sqlSave(ctx context.Context) (*PendingOp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PendingOpCreate) createSpec() (*PendingOp, *sqlgraph.CreateSpec) {
	var (
		_node = &PendingOp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pendingop.Table, sqlgraph.NewFieldSpec(pendingop.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderThreadIds(); ok {
		_spec.SetField(pendingop.FieldProviderThreadIds, field.TypeJSON, value)
		_node.ProviderThreadIds = value
	}
	if value, ok := _c.mutation.OpType(); ok {
		_spec.SetField(pendingop.FieldOpType, field.TypeEnum, value)
		_node.OpType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(pendingop.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pendingop.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(pendingop.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(pendingop.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(pendingop.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(pendingop.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pendingop.AccountTable,
			Columns: []string{pendingop.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_pending_ops = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PendingOp.Create().
//		SetProviderThreadIds(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PendingOpUpsert) {
//			SetProviderThreadIds(v+v).
//		}).
//		Exec(ctx)
func (_c *PendingOpCreate) OnConflict(opts ...sql.ConflictOption) *PendingOpUpsertOne {
	_c.conflict = opts
	return &PendingOpUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PendingOpCreate) OnConflictColumns(columns ...string) *PendingOpUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PendingOpUpsertOne{
		create: _c,
	}
}

type (
	// PendingOpUpsertOne is the builder for "upsert"-ing
	//  one PendingOp node.
	PendingOpUpsertOne struct {
		create *PendingOpCreate
	}

	// PendingOpUpsert is the "OnConflict" setter.
	PendingOpUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (u *PendingOpUpsert) SetProviderThreadIds(v []string) *PendingOpUpsert {
	u.Set(pendingop.FieldProviderThreadIds, v)
	return u
}

// UpdateProviderThreadIds sets the "provider_thread_ids" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateProviderThreadIds() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldProviderThreadIds)
	return u
}

// SetOpType sets the "op_type" field.
func (u *PendingOpUpsert) SetOpType(v pendingop.OpType) *PendingOpUpsert {
	u.Set(pendingop.FieldOpType, v)
	return u
}

// UpdateOpType sets the "op_type" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateOpType() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldOpType)
	return u
}

// SetPayload sets the "payload" field.
func (u *PendingOpUpsert) SetPayload(v map[string]interface{}) *PendingOpUpsert {
	u.Set(pendingop.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdatePayload() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldPayload)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *PendingOpUpsert) SetAttempts(v int) *PendingOpUpsert {
	u.Set(pendingop.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateAttempts() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *PendingOpUpsert) AddAttempts(v int) *PendingOpUpsert {
	u.Add(pendingop.FieldAttempts, v)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *PendingOpUpsert) SetNextAttemptAt(v time.Time) *PendingOpUpsert {
	u.Set(pendingop.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateNextAttemptAt() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldNextAttemptAt)
	return u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *PendingOpUpsert) ClearNextAttemptAt() *PendingOpUpsert {
	u.SetNull(pendingop.FieldNextAttemptAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *PendingOpUpsert) SetLastError(v string) *PendingOpUpsert {
	u.Set(pendingop.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateLastError() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldLastError)
	return u
}

// SetState sets the "state" field.
func (u *PendingOpUpsert) SetState(v pendingop.State) *PendingOpUpsert {
	u.Set(pendingop.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PendingOpUpsert) UpdateState() *PendingOpUpsert {
	u.SetExcluded(pendingop.FieldState)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PendingOpUpsertOne) UpdateNewValues() *PendingOpUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pendingop.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PendingOpUpsertOne) Ignore() *PendingOpUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PendingOpUpsertOne) DoNothing() *PendingOpUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PendingOpCreate.OnConflict
// documentation for more info.
func (u *PendingOpUpsertOne) Update(set func(*PendingOpUpsert)) *PendingOpUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PendingOpUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (u *PendingOpUpsertOne) SetProviderThreadIds(v []string) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetProviderThreadIds(v)
	})
}

// UpdateProviderThreadIds sets the "provider_thread_ids" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateProviderThreadIds() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateProviderThreadIds()
	})
}

// SetOpType sets the "op_type" field.
func (u *PendingOpUpsertOne) SetOpType(v pendingop.OpType) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetOpType(v)
	})
}

// UpdateOpType sets the "op_type" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateOpType() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateOpType()
	})
}

// SetPayload sets the "payload" field.
func (u *PendingOpUpsertOne) SetPayload(v map[string]interface{}) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdatePayload() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdatePayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *PendingOpUpsertOne) SetAttempts(v int) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *PendingOpUpsertOne) AddAttempts(v int) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateAttempts() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *PendingOpUpsertOne) SetNextAttemptAt(v time.Time) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateNextAttemptAt() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *PendingOpUpsertOne) ClearNextAttemptAt() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *PendingOpUpsertOne) SetLastError(v string) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateLastError() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateLastError()
	})
}

// SetState sets the "state" field.
func (u *PendingOpUpsertOne) SetState(v pendingop.State) *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PendingOpUpsertOne) UpdateState() *PendingOpUpsertOne {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateState()
	})
}

// Exec executes the query.
func (u *PendingOpUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PendingOpCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PendingOpUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PendingOpUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PendingOpUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PendingOpCreateBulk is the builder for creating many PendingOp entities in bulk.
type PendingOpCreateBulk struct {
	config
	err      error
	builders []*PendingOpCreate
	conflict []sql.ConflictOption
}

// Save creates the PendingOp entities in the database.
func (_c *PendingOpCreateBulk) Save(ctx context.Context) ([]*PendingOp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PendingOp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PendingOpMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PendingOpCreateBulk) SaveX(ctx context.Context) []*PendingOp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PendingOpCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PendingOpCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PendingOp.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PendingOpUpsert) {
//			SetProviderThreadIds(v+v).
//		}).
//		Exec(ctx)
func (_c *PendingOpCreateBulk) OnConflict(opts ...sql.ConflictOption) *PendingOpUpsertBulk {
	_c.conflict = opts
	return &PendingOpUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PendingOpCreateBulk) OnConflictColumns(columns ...string) *PendingOpUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PendingOpUpsertBulk{
		create: _c,
	}
}

// PendingOpUpsertBulk is the builder for "upsert"-ing
// a bulk of PendingOp nodes.
type PendingOpUpsertBulk struct {
	create *PendingOpCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PendingOpUpsertBulk) UpdateNewValues() *PendingOpUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pendingop.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PendingOp.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PendingOpUpsertBulk) Ignore() *PendingOpUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PendingOpUpsertBulk) DoNothing() *PendingOpUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PendingOpCreateBulk.OnConflict
// documentation for more info.
func (u *PendingOpUpsertBulk) Update(set func(*PendingOpUpsert)) *PendingOpUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PendingOpUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (u *PendingOpUpsertBulk) SetProviderThreadIds(v []string) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetProviderThreadIds(v)
	})
}

// UpdateProviderThreadIds sets the "provider_thread_ids" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateProviderThreadIds() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateProviderThreadIds()
	})
}

// SetOpType sets the "op_type" field.
func (u *PendingOpUpsertBulk) SetOpType(v pendingop.OpType) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetOpType(v)
	})
}

// UpdateOpType sets the "op_type" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateOpType() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateOpType()
	})
}

// SetPayload sets the "payload" field.
func (u *PendingOpUpsertBulk) SetPayload(v map[string]interface{}) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdatePayload() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdatePayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *PendingOpUpsertBulk) SetAttempts(v int) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *PendingOpUpsertBulk) AddAttempts(v int) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateAttempts() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *PendingOpUpsertBulk) SetNextAttemptAt(v time.Time) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateNextAttemptAt() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *PendingOpUpsertBulk) ClearNextAttemptAt() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *PendingOpUpsertBulk) SetLastError(v string) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateLastError() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateLastError()
	})
}

// SetState sets the "state" field.
func (u *PendingOpUpsertBulk) SetState(v pendingop.State) *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PendingOpUpsertBulk) UpdateState() *PendingOpUpsertBulk {
	return u.Update(func(s *PendingOpUpsert) {
		s.UpdateState()
	})
}

// Exec executes the query.
func (u *PendingOpUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PendingOpCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PendingOpCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PendingOpUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
