// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/pendingop"
	"github.com/arqueon/dankmail/core/ent/predicate"
	"github.com/google/uuid"
)

// PendingOpUpdate is the builder for updating PendingOp entities.
type PendingOpUpdate struct {
	config
	hooks     []Hook
	mutation  *PendingOpMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PendingOpUpdate builder.
func (_u *PendingOpUpdate) Where(ps ...predicate.PendingOp) *PendingOpUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (_u *PendingOpUpdate) SetProviderThreadIds(v []string) *PendingOpUpdate {
	_u.mutation.SetProviderThreadIds(v)
	return _u
}

// AppendProviderThreadIds appends value to the "provider_thread_ids" field.
func (_u *PendingOpUpdate) AppendProviderThreadIds(v []string) *PendingOpUpdate {
	_u.mutation.AppendProviderThreadIds(v)
	return _u
}

// SetOpType sets the "op_type" field.
func (_u *PendingOpUpdate) SetOpType(v pendingop.OpType) *PendingOpUpdate {
	_u.mutation.SetOpType(v)
	return _u
}

// SetNillableOpType sets the "op_type" field if the given value is not nil.
func (_u *PendingOpUpdate) SetNillableOpType(v *pendingop.OpType) *PendingOpUpdate {
	if v != nil {
		_u.SetOpType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PendingOpUpdate) SetPayload(v map[string]interface{}) *PendingOpUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *PendingOpUpdate) SetAttempts(v int) *PendingOpUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *PendingOpUpdate) SetNillableAttempts(v *int) *PendingOpUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *PendingOpUpdate) AddAttempts(v int) *PendingOpUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PendingOpUpdate) SetNextAttemptAt(v time.Time) *PendingOpUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PendingOpUpdate) SetNillableNextAttemptAt(v *time.Time) *PendingOpUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PendingOpUpdate) ClearNextAttemptAt() *PendingOpUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PendingOpUpdate) SetLastError(v string) *PendingOpUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PendingOpUpdate) SetNillableLastError(v *string) *PendingOpUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *PendingOpUpdate) SetState(v pendingop.State) *PendingOpUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PendingOpUpdate) SetNillableState(v *pendingop.State) *PendingOpUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *PendingOpUpdate) SetAccountID(id uuid.UUID) *PendingOpUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PendingOpUpdate) SetAccount(v *Account) *PendingOpUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PendingOpMutation object of the builder.
func (_u *PendingOpUpdate) Mutation() *PendingOpMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PendingOpUpdate) ClearAccount() *PendingOpUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PendingOpUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PendingOpUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PendingOpUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PendingOpUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PendingOpUpdate) check() error {
	if v, ok := _u.mutation.OpType(); ok {
		if err := pendingop.OpTypeValidator(v); err != nil {
			return &ValidationError{Name: "op_type", err: fmt.Errorf(`ent: validator failed for field "PendingOp.op_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := pendingop.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PendingOp.state": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PendingOp.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PendingOpUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PendingOpUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PendingOpUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pendingop.Table, pendingop.Columns, sqlgraph.NewFieldSpec(pendingop.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderThreadIds(); ok {
		_spec.SetField(pendingop.FieldProviderThreadIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProviderThreadIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pendingop.FieldProviderThreadIds, value)
		})
	}
	if value, ok := _u.mutation.OpType(); ok {
		_spec.SetField(pendingop.FieldOpType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(pendingop.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(pendingop.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(pendingop.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(pendingop.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(pendingop.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(pendingop.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(pendingop.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pendingop.AccountTable,
			Columns: []string{pendingop.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pendingop.AccountTable,
			Columns: []string{pendingop.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pendingop.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PendingOpUpdateOne is the builder for updating a single PendingOp entity.
type PendingOpUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PendingOpMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetProviderThreadIds sets the "provider_thread_ids" field.
func (_u *PendingOpUpdateOne) SetProviderThreadIds(v []string) *PendingOpUpdateOne {
	_u.mutation.SetProviderThreadIds(v)
	return _u
}

// AppendProviderThreadIds appends value to the "provider_thread_ids" field.
func (_u *PendingOpUpdateOne) AppendProviderThreadIds(v []string) *PendingOpUpdateOne {
	_u.mutation.AppendProviderThreadIds(v)
	return _u
}

// SetOpType sets the "op_type" field.
func (_u *PendingOpUpdateOne) SetOpType(v pendingop.OpType) *PendingOpUpdateOne {
	_u.mutation.SetOpType(v)
	return _u
}

// SetNillableOpType sets the "op_type" field if the given value is not nil.
func (_u *PendingOpUpdateOne) SetNillableOpType(v *pendingop.OpType) *PendingOpUpdateOne {
	if v != nil {
		_u.SetOpType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *PendingOpUpdateOne) SetPayload(v map[string]interface{}) *PendingOpUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *PendingOpUpdateOne) SetAttempts(v int) *PendingOpUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *PendingOpUpdateOne) SetNillableAttempts(v *int) *PendingOpUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *PendingOpUpdateOne) AddAttempts(v int) *PendingOpUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PendingOpUpdateOne) SetNextAttemptAt(v time.Time) *PendingOpUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PendingOpUpdateOne) SetNillableNextAttemptAt(v *time.Time) *PendingOpUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PendingOpUpdateOne) ClearNextAttemptAt() *PendingOpUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PendingOpUpdateOne) SetLastError(v string) *PendingOpUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PendingOpUpdateOne) SetNillableLastError(v *string) *PendingOpUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *PendingOpUpdateOne) SetState(v pendingop.State) *PendingOpUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PendingOpUpdateOne) SetNillableState(v *pendingop.State) *PendingOpUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *PendingOpUpdateOne) SetAccountID(id uuid.UUID) *PendingOpUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PendingOpUpdateOne) SetAccount(v *Account) *PendingOpUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PendingOpMutation object of the builder.
func (_u *PendingOpUpdateOne) Mutation() *PendingOpMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PendingOpUpdateOne) ClearAccount() *PendingOpUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the PendingOpUpdate builder.
func (_u *PendingOpUpdateOne) Where(ps ...predicate.PendingOp) *PendingOpUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PendingOpUpdateOne) Select(field string, fields ...string) *PendingOpUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PendingOp entity.
func (_u *PendingOpUpdateOne) Save(ctx context.Context) (*PendingOp, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PendingOpUpdateOne) SaveX(ctx context.Context) *PendingOp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PendingOpUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PendingOpUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PendingOpUpdateOne) check() error {
	if v, ok := _u.mutation.OpType(); ok {
		if err := pendingop.OpTypeValidator(v); err != nil {
			return &ValidationError{Name: "op_type", err: fmt.Errorf(`ent: validator failed for field "PendingOp.op_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := pendingop.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PendingOp.state": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PendingOp.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PendingOpUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PendingOpUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PendingOpUpdateOne) sqlSave(ctx context.Context) (_node *PendingOp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pendingop.Table, pendingop.Columns, sqlgraph.NewFieldSpec(pendingop.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PendingOp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pendingop.FieldID)
		for _, f := range fields {
			if !pendingop.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pendingop.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderThreadIds(); ok {
		_spec.SetField(pendingop.FieldProviderThreadIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProviderThreadIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pendingop.FieldProviderThreadIds, value)
		})
	}
	if value, ok := _u.mutation.OpType(); ok {
		_spec.SetField(pendingop.FieldOpType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(pendingop.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(pendingop.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(pendingop.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(pendingop.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(pendingop.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(pendingop.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(pendingop.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pendingop.AccountTable,
			Columns: []string{pendingop.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pendingop.AccountTable,
			Columns: []string{pendingop.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PendingOp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pendingop.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
