// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/contact"
	"github.com/arqueon/dankmail/core/ent/message"
	"github.com/arqueon/dankmail/core/ent/notifyrule"
	"github.com/arqueon/dankmail/core/ent/pendingop"
	"github.com/arqueon/dankmail/core/ent/schema"
	"github.com/arqueon/dankmail/core/ent/thread"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescDisplayName is the schema descriptor for display_name field.
	accountDescDisplayName := accountFields[3].Descriptor()
	// account.DefaultDisplayName holds the default value on creation for the display_name field.
	account.DefaultDisplayName = accountDescDisplayName.Default.(string)
	// accountDescConfig is the schema descriptor for config field.
	accountDescConfig := accountFields[4].Descriptor()
	// account.DefaultConfig holds the default value on creation for the config field.
	account.DefaultConfig = accountDescConfig.Default.(map[string]interface{})
	// accountDescSyncCursor is the schema descriptor for sync_cursor field.
	accountDescSyncCursor := accountFields[5].Descriptor()
	// account.DefaultSyncCursor holds the default value on creation for the sync_cursor field.
	account.DefaultSyncCursor = accountDescSyncCursor.Default.(string)
	// accountDescLastError is the schema descriptor for last_error field.
	accountDescLastError := accountFields[8].Descriptor()
	// account.DefaultLastError holds the default value on creation for the last_error field.
	account.DefaultLastError = accountDescLastError.Default.(string)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[9].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescName is the schema descriptor for name field.
	contactDescName := contactFields[1].Descriptor()
	// contact.DefaultName holds the default value on creation for the name field.
	contact.DefaultName = contactDescName.Default.(string)
	// contactDescWeight is the schema descriptor for weight field.
	contactDescWeight := contactFields[3].Descriptor()
	// contact.DefaultWeight holds the default value on creation for the weight field.
	contact.DefaultWeight = contactDescWeight.Default.(int)
	// contactDescLastSeen is the schema descriptor for last_seen field.
	contactDescLastSeen := contactFields[4].Descriptor()
	// contact.DefaultLastSeen holds the default value on creation for the last_seen field.
	contact.DefaultLastSeen = contactDescLastSeen.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescRfc822MessageID is the schema descriptor for rfc822_message_id field.
	messageDescRfc822MessageID := messageFields[1].Descriptor()
	// message.DefaultRfc822MessageID holds the default value on creation for the rfc822_message_id field.
	message.DefaultRfc822MessageID = messageDescRfc822MessageID.Default.(string)
	// messageDescFrom is the schema descriptor for from field.
	messageDescFrom := messageFields[2].Descriptor()
	// message.DefaultFrom holds the default value on creation for the from field.
	message.DefaultFrom = messageDescFrom.Default.(string)
	// messageDescTo is the schema descriptor for to field.
	messageDescTo := messageFields[3].Descriptor()
	// message.DefaultTo holds the default value on creation for the to field.
	message.DefaultTo = messageDescTo.Default.([]string)
	// messageDescCc is the schema descriptor for cc field.
	messageDescCc := messageFields[4].Descriptor()
	// message.DefaultCc holds the default value on creation for the cc field.
	message.DefaultCc = messageDescCc.Default.([]string)
	// messageDescSnippet is the schema descriptor for snippet field.
	messageDescSnippet := messageFields[6].Descriptor()
	// message.DefaultSnippet holds the default value on creation for the snippet field.
	message.DefaultSnippet = messageDescSnippet.Default.(string)
	// messageDescBodyText is the schema descriptor for body_text field.
	messageDescBodyText := messageFields[7].Descriptor()
	// message.DefaultBodyText holds the default value on creation for the body_text field.
	message.DefaultBodyText = messageDescBodyText.Default.(string)
	// messageDescReplyHeaders is the schema descriptor for reply_headers field.
	messageDescReplyHeaders := messageFields[8].Descriptor()
	// message.DefaultReplyHeaders holds the default value on creation for the reply_headers field.
	message.DefaultReplyHeaders = messageDescReplyHeaders.Default.(map[string]string)
	notifyruleFields := schema.NotifyRule{}.Fields()
	_ = notifyruleFields
	// notifyruleDescEnabled is the schema descriptor for enabled field.
	notifyruleDescEnabled := notifyruleFields[1].Descriptor()
	// notifyrule.DefaultEnabled holds the default value on creation for the enabled field.
	notifyrule.DefaultEnabled = notifyruleDescEnabled.Default.(bool)
	// notifyruleDescNotify is the schema descriptor for notify field.
	notifyruleDescNotify := notifyruleFields[2].Descriptor()
	// notifyrule.DefaultNotify holds the default value on creation for the notify field.
	notifyrule.DefaultNotify = notifyruleDescNotify.Default.(bool)
	// notifyruleDescSound is the schema descriptor for sound field.
	notifyruleDescSound := notifyruleFields[3].Descriptor()
	// notifyrule.DefaultSound holds the default value on creation for the sound field.
	notifyrule.DefaultSound = notifyruleDescSound.Default.(string)
	pendingopFields := schema.PendingOp{}.Fields()
	_ = pendingopFields
	// pendingopDescProviderThreadIds is the schema descriptor for provider_thread_ids field.
	pendingopDescProviderThreadIds := pendingopFields[0].Descriptor()
	// pendingop.DefaultProviderThreadIds holds the default value on creation for the provider_thread_ids field.
	pendingop.DefaultProviderThreadIds = pendingopDescProviderThreadIds.Default.([]string)
	// pendingopDescPayload is the schema descriptor for payload field.
	pendingopDescPayload := pendingopFields[2].Descriptor()
	// pendingop.DefaultPayload holds the default value on creation for the payload field.
	pendingop.DefaultPayload = pendingopDescPayload.Default.(map[string]interface{})
	// pendingopDescCreatedAt is the schema descriptor for created_at field.
	pendingopDescCreatedAt := pendingopFields[3].Descriptor()
	// pendingop.DefaultCreatedAt holds the default value on creation for the created_at field.
	pendingop.DefaultCreatedAt = pendingopDescCreatedAt.Default.(func() time.Time)
	// pendingopDescAttempts is the schema descriptor for attempts field.
	pendingopDescAttempts := pendingopFields[4].Descriptor()
	// pendingop.DefaultAttempts holds the default value on creation for the attempts field.
	pendingop.DefaultAttempts = pendingopDescAttempts.Default.(int)
	// pendingopDescLastError is the schema descriptor for last_error field.
	pendingopDescLastError := pendingopFields[6].Descriptor()
	// pendingop.DefaultLastError holds the default value on creation for the last_error field.
	pendingop.DefaultLastError = pendingopDescLastError.Default.(string)
	threadFields := schema.Thread{}.Fields()
	_ = threadFields
	// threadDescSubject is the schema descriptor for subject field.
	threadDescSubject := threadFields[1].Descriptor()
	// thread.DefaultSubject holds the default value on creation for the subject field.
	thread.DefaultSubject = threadDescSubject.Default.(string)
	// threadDescSnippet is the schema descriptor for snippet field.
	threadDescSnippet := threadFields[2].Descriptor()
	// thread.DefaultSnippet holds the default value on creation for the snippet field.
	thread.DefaultSnippet = threadDescSnippet.Default.(string)
	// threadDescParticipants is the schema descriptor for participants field.
	threadDescParticipants := threadFields[4].Descriptor()
	// thread.DefaultParticipants holds the default value on creation for the participants field.
	thread.DefaultParticipants = threadDescParticipants.Default.([]string)
	// threadDescUnread is the schema descriptor for unread field.
	threadDescUnread := threadFields[5].Descriptor()
	// thread.DefaultUnread holds the default value on creation for the unread field.
	thread.DefaultUnread = threadDescUnread.Default.(bool)
	// threadDescStarred is the schema descriptor for starred field.
	threadDescStarred := threadFields[6].Descriptor()
	// thread.DefaultStarred holds the default value on creation for the starred field.
	thread.DefaultStarred = threadDescStarred.Default.(bool)
	// threadDescInInbox is the schema descriptor for in_inbox field.
	threadDescInInbox := threadFields[7].Descriptor()
	// thread.DefaultInInbox holds the default value on creation for the in_inbox field.
	thread.DefaultInInbox = threadDescInInbox.Default.(bool)
	// threadDescLabels is the schema descriptor for labels field.
	threadDescLabels := threadFields[8].Descriptor()
	// thread.DefaultLabels holds the default value on creation for the labels field.
	thread.DefaultLabels = threadDescLabels.Default.([]string)
	// threadDescMessageCount is the schema descriptor for message_count field.
	threadDescMessageCount := threadFields[10].Descriptor()
	// thread.DefaultMessageCount holds the default value on creation for the message_count field.
	thread.DefaultMessageCount = threadDescMessageCount.Default.(int)
	// threadDescHasAttachments is the schema descriptor for has_attachments field.
	threadDescHasAttachments := threadFields[11].Descriptor()
	// thread.DefaultHasAttachments holds the default value on creation for the has_attachments field.
	thread.DefaultHasAttachments = threadDescHasAttachments.Default.(bool)
}
