// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/message"
	"github.com/arqueon/dankmail/core/ent/thread"
	"github.com/google/uuid"
)

// ThreadCreate is the builder for creating a Thread entity.
type ThreadCreate struct {
	config
	mutation *ThreadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderThreadID sets the "provider_thread_id" field.
func (_c *ThreadCreate) SetProviderThreadID(v string) *ThreadCreate {
	_c.mutation.SetProviderThreadID(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *ThreadCreate) SetSubject(v string) *ThreadCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableSubject(v *string) *ThreadCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetSnippet sets the "snippet" field.
func (_c *ThreadCreate) SetSnippet(v string) *ThreadCreate {
	_c.mutation.SetSnippet(v)
	return _c
}

// SetNillableSnippet sets the "snippet" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableSnippet(v *string) *ThreadCreate {
	if v != nil {
		_c.SetSnippet(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ThreadCreate) SetLastMessageAt(v time.Time) *ThreadCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetParticipants sets the "participants" field.
func (_c *ThreadCreate) SetParticipants(v []string) *ThreadCreate {
	_c.mutation.SetParticipants(v)
	return _c
}

// SetUnread sets the "unread" field.
func (_c *ThreadCreate) SetUnread(v bool) *ThreadCreate {
	_c.mutation.SetUnread(v)
	return _c
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableUnread(v *bool) *ThreadCreate {
	if v != nil {
		_c.SetUnread(*v)
	}
	return _c
}

// SetStarred sets the "starred" field.
func (_c *ThreadCreate) SetStarred(v bool) *ThreadCreate {
	_c.mutation.SetStarred(v)
	return _c
}

// SetNillableStarred sets the "starred" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableStarred(v *bool) *ThreadCreate {
	if v != nil {
		_c.SetStarred(*v)
	}
	return _c
}

// SetInInbox sets the "in_inbox" field.
func (_c *ThreadCreate) SetInInbox(v bool) *ThreadCreate {
	_c.mutation.SetInInbox(v)
	return _c
}

// SetNillableInInbox sets the "in_inbox" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableInInbox(v *bool) *ThreadCreate {
	if v != nil {
		_c.SetInInbox(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *ThreadCreate) SetLabels(v []string) *ThreadCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (_c *ThreadCreate) SetSnoozedUntil(v time.Time) *ThreadCreate {
	_c.mutation.SetSnoozedUntil(v)
	return _c
}

// SetNillableSnoozedUntil sets the "snoozed_until" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableSnoozedUntil(v *time.Time) *ThreadCreate {
	if v != nil {
		_c.SetSnoozedUntil(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *ThreadCreate) SetMessageCount(v int) *ThreadCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableMessageCount(v *int) *ThreadCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetHasAttachments sets the "has_attachments" field.
func (_c *ThreadCreate) SetHasAttachments(v bool) *ThreadCreate {
	_c.mutation.SetHasAttachments(v)
	return _c
}

// SetNillableHasAttachments sets the "has_attachments" field if the given value is not nil.
func (_c *ThreadCreate) SetNillableHasAttachments(v *bool) *ThreadCreate {
	if v != nil {
		_c.SetHasAttachments(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *ThreadCreate) SetAccountID(id uuid.UUID) *ThreadCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ThreadCreate) SetAccount(v *Account) *ThreadCreate {
	return _c.SetAccountID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ThreadCreate) AddMessageIDs(ids ...int) *ThreadCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ThreadCreate) AddMessages(v ...*Message) *ThreadCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_c *ThreadCreate) Mutation() *ThreadMutation {
	return _c.mutation
}

// Save creates the Thread in the database.
func (_c *ThreadCreate) Save(ctx context.Context) (*Thread, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThreadCreate) SaveX(ctx context.Context) *Thread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThreadCreate) defaults() {
	if _, ok := _c.mutation.Subject(); !ok {
		v := thread.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.Snippet(); !ok {
		v := thread.DefaultSnippet
		_c.mutation.SetSnippet(v)
	}
	if _, ok := _c.mutation.Participants(); !ok {
		v := thread.DefaultParticipants
		_c.mutation.SetParticipants(v)
	}
	if _, ok := _c.mutation.Unread(); !ok {
		v := thread.DefaultUnread
		_c.mutation.SetUnread(v)
	}
	if _, ok := _c.mutation.Starred(); !ok {
		v := thread.DefaultStarred
		_c.mutation.SetStarred(v)
	}
	if _, ok := _c.mutation.InInbox(); !ok {
		v := thread.DefaultInInbox
		_c.mutation.SetInInbox(v)
	}
	if _, ok := _c.mutation.Labels(); !ok {
		v := thread.DefaultLabels
		_c.mutation.SetLabels(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := thread.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
	if _, ok := _c.mutation.HasAttachments(); !ok {
		v := thread.DefaultHasAttachments
		_c.mutation.SetHasAttachments(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThreadCreate) check() error {
	if _, ok := _c.mutation.ProviderThreadID(); !ok {
		return &ValidationError{Name: "provider_thread_id", err: errors.New(`ent: missing required field "Thread.provider_thread_id"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Thread.subject"`)}
	}
	if _, ok := _c.mutation.Snippet(); !ok {
		return &ValidationError{Name: "snippet", err: errors.New(`ent: missing required field "Thread.snippet"`)}
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		return &ValidationError{Name: "last_message_at", err: errors.New(`ent: missing required field "Thread.last_message_at"`)}
	}
	if _, ok := _c.mutation.Participants(); !ok {
		return &ValidationError{Name: "participants", err: errors.New(`ent: missing required field "Thread.participants"`)}
	}
	if _, ok := _c.mutation.Unread(); !ok {
		return &ValidationError{Name: "unread", err: errors.New(`ent: missing required field "Thread.unread"`)}
	}
	if _, ok := _c.mutation.Starred(); !ok {
		return &ValidationError{Name: "starred", err: errors.New(`ent: missing required field "Thread.starred"`)}
	}
	if _, ok := _c.mutation.InInbox(); !ok {
		return &ValidationError{Name: "in_inbox", err: errors.New(`ent: missing required field "Thread.in_inbox"`)}
	}
	if _, ok := _c.mutation.Labels(); !ok {
		return &ValidationError{Name: "labels", err: errors.New(`ent: missing required field "Thread.labels"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "Thread.message_count"`)}
	}
	if _, ok := _c.mutation.HasAttachments(); !ok {
		return &ValidationError{Name: "has_attachments", err: errors.New(`ent: missing required field "Thread.has_attachments"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "Thread.account"`)}
	}
	return nil
}

func (_c *ThreadCreate) sqlSave(ctx context.Context) (*Thread, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThreadCreate) createSpec() (*Thread, *sqlgraph.CreateSpec) {
	var (
		_node = &Thread{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(thread.Table, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderThreadID(); ok {
		_spec.SetField(thread.FieldProviderThreadID, field.TypeString, value)
		_node.ProviderThreadID = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(thread.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Snippet(); ok {
		_spec.SetField(thread.FieldSnippet, field.TypeString, value)
		_node.Snippet = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(thread.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = value
	}
	if value, ok := _c.mutation.Participants(); ok {
		_spec.SetField(thread.FieldParticipants, field.TypeJSON, value)
		_node.Participants = value
	}
	if value, ok := _c.mutation.Unread(); ok {
		_spec.SetField(thread.FieldUnread, field.TypeBool, value)
		_node.Unread = value
	}
	if value, ok := _c.mutation.Starred(); ok {
		_spec.SetField(thread.FieldStarred, field.TypeBool, value)
		_node.Starred = value
	}
	if value, ok := _c.mutation.InInbox(); ok {
		_spec.SetField(thread.FieldInInbox, field.TypeBool, value)
		_node.InInbox = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(thread.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.SnoozedUntil(); ok {
		_spec.SetField(thread.FieldSnoozedUntil, field.TypeTime, value)
		_node.SnoozedUntil = &value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(thread.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.HasAttachments(); ok {
		_spec.SetField(thread.FieldHasAttachments, field.TypeBool, value)
		_node.HasAttachments = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AccountTable,
			Columns: []string{thread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_threads = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Thread.Create().
//		SetProviderThreadID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadUpsert) {
//			SetProviderThreadID(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadCreate) OnConflict(opts ...sql.ConflictOption) *ThreadUpsertOne {
	_c.conflict = opts
	return &ThreadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadCreate) OnConflictColumns(columns ...string) *ThreadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadUpsertOne{
		create: _c,
	}
}

type (
	// ThreadUpsertOne is the builder for "upsert"-ing
	//  one Thread node.
	ThreadUpsertOne struct {
		create *ThreadCreate
	}

	// ThreadUpsert is the "OnConflict" setter.
	ThreadUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderThreadID sets the "provider_thread_id" field.
func (u *ThreadUpsert) SetProviderThreadID(v string) *ThreadUpsert {
	u.Set(thread.FieldProviderThreadID, v)
	return u
}

// UpdateProviderThreadID sets the "provider_thread_id" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateProviderThreadID() *ThreadUpsert {
	u.SetExcluded(thread.FieldProviderThreadID)
	return u
}

// SetSubject sets the "subject" field.
func (u *ThreadUpsert) SetSubject(v string) *ThreadUpsert {
	u.Set(thread.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateSubject() *ThreadUpsert {
	u.SetExcluded(thread.FieldSubject)
	return u
}

// SetSnippet sets the "snippet" field.
func (u *ThreadUpsert) SetSnippet(v string) *ThreadUpsert {
	u.Set(thread.FieldSnippet, v)
	return u
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateSnippet() *ThreadUpsert {
	u.SetExcluded(thread.FieldSnippet)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ThreadUpsert) SetLastMessageAt(v time.Time) *ThreadUpsert {
	u.Set(thread.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateLastMessageAt() *ThreadUpsert {
	u.SetExcluded(thread.FieldLastMessageAt)
	return u
}

// SetParticipants sets the "participants" field.
func (u *ThreadUpsert) SetParticipants(v []string) *ThreadUpsert {
	u.Set(thread.FieldParticipants, v)
	return u
}

// UpdateParticipants sets the "participants" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateParticipants() *ThreadUpsert {
	u.SetExcluded(thread.FieldParticipants)
	return u
}

// SetUnread sets the "unread" field.
func (u *ThreadUpsert) SetUnread(v bool) *ThreadUpsert {
	u.Set(thread.FieldUnread, v)
	return u
}

// UpdateUnread sets the "unread" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateUnread() *ThreadUpsert {
	u.SetExcluded(thread.FieldUnread)
	return u
}

// SetStarred sets the "starred" field.
func (u *ThreadUpsert) SetStarred(v bool) *ThreadUpsert {
	u.Set(thread.FieldStarred, v)
	return u
}

// UpdateStarred sets the "starred" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateStarred() *ThreadUpsert {
	u.SetExcluded(thread.FieldStarred)
	return u
}

// SetInInbox sets the "in_inbox" field.
func (u *ThreadUpsert) SetInInbox(v bool) *ThreadUpsert {
	u.Set(thread.FieldInInbox, v)
	return u
}

// UpdateInInbox sets the "in_inbox" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateInInbox() *ThreadUpsert {
	u.SetExcluded(thread.FieldInInbox)
	return u
}

// SetLabels sets the "labels" field.
func (u *ThreadUpsert) SetLabels(v []string) *ThreadUpsert {
	u.Set(thread.FieldLabels, v)
	return u
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateLabels() *ThreadUpsert {
	u.SetExcluded(thread.FieldLabels)
	return u
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (u *ThreadUpsert) SetSnoozedUntil(v time.Time) *ThreadUpsert {
	u.Set(thread.FieldSnoozedUntil, v)
	return u
}

// UpdateSnoozedUntil sets the "snoozed_until" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateSnoozedUntil() *ThreadUpsert {
	u.SetExcluded(thread.FieldSnoozedUntil)
	return u
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (u *ThreadUpsert) ClearSnoozedUntil() *ThreadUpsert {
	u.SetNull(thread.FieldSnoozedUntil)
	return u
}

// SetMessageCount sets the "message_count" field.
func (u *ThreadUpsert) SetMessageCount(v int) *ThreadUpsert {
	u.Set(thread.FieldMessageCount, v)
	return u
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateMessageCount() *ThreadUpsert {
	u.SetExcluded(thread.FieldMessageCount)
	return u
}

// AddMessageCount adds v to the "message_count" field.
func (u *ThreadUpsert) AddMessageCount(v int) *ThreadUpsert {
	u.Add(thread.FieldMessageCount, v)
	return u
}

// SetHasAttachments sets the "has_attachments" field.
func (u *ThreadUpsert) SetHasAttachments(v bool) *ThreadUpsert {
	u.Set(thread.FieldHasAttachments, v)
	return u
}

// UpdateHasAttachments sets the "has_attachments" field to the value that was provided on create.
func (u *ThreadUpsert) UpdateHasAttachments() *ThreadUpsert {
	u.SetExcluded(thread.FieldHasAttachments)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ThreadUpsertOne) UpdateNewValues() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ThreadUpsertOne) Ignore() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadUpsertOne) DoNothing() *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadCreate.OnConflict
// documentation for more info.
func (u *ThreadUpsertOne) Update(set func(*ThreadUpsert)) *ThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderThreadID sets the "provider_thread_id" field.
func (u *ThreadUpsertOne) SetProviderThreadID(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetProviderThreadID(v)
	})
}

// UpdateProviderThreadID sets the "provider_thread_id" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateProviderThreadID() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateProviderThreadID()
	})
}

// SetSubject sets the "subject" field.
func (u *ThreadUpsertOne) SetSubject(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateSubject() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSubject()
	})
}

// SetSnippet sets the "snippet" field.
func (u *ThreadUpsertOne) SetSnippet(v string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSnippet(v)
	})
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateSnippet() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSnippet()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ThreadUpsertOne) SetLastMessageAt(v time.Time) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateLastMessageAt() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetParticipants sets the "participants" field.
func (u *ThreadUpsertOne) SetParticipants(v []string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetParticipants(v)
	})
}

// UpdateParticipants sets the "participants" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateParticipants() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateParticipants()
	})
}

// SetUnread sets the "unread" field.
func (u *ThreadUpsertOne) SetUnread(v bool) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetUnread(v)
	})
}

// UpdateUnread sets the "unread" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateUnread() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateUnread()
	})
}

// SetStarred sets the "starred" field.
func (u *ThreadUpsertOne) SetStarred(v bool) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetStarred(v)
	})
}

// UpdateStarred sets the "starred" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateStarred() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateStarred()
	})
}

// SetInInbox sets the "in_inbox" field.
func (u *ThreadUpsertOne) SetInInbox(v bool) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetInInbox(v)
	})
}

// UpdateInInbox sets the "in_inbox" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateInInbox() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateInInbox()
	})
}

// SetLabels sets the "labels" field.
func (u *ThreadUpsertOne) SetLabels(v []string) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateLabels() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLabels()
	})
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (u *ThreadUpsertOne) SetSnoozedUntil(v time.Time) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSnoozedUntil(v)
	})
}

// UpdateSnoozedUntil sets the "snoozed_until" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateSnoozedUntil() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSnoozedUntil()
	})
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (u *ThreadUpsertOne) ClearSnoozedUntil() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.ClearSnoozedUntil()
	})
}

// SetMessageCount sets the "message_count" field.
func (u *ThreadUpsertOne) SetMessageCount(v int) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetMessageCount(v)
	})
}

// AddMessageCount adds v to the "message_count" field.
func (u *ThreadUpsertOne) AddMessageCount(v int) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.AddMessageCount(v)
	})
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateMessageCount() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateMessageCount()
	})
}

// SetHasAttachments sets the "has_attachments" field.
func (u *ThreadUpsertOne) SetHasAttachments(v bool) *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.SetHasAttachments(v)
	})
}

// UpdateHasAttachments sets the "has_attachments" field to the value that was provided on create.
func (u *ThreadUpsertOne) UpdateHasAttachments() *ThreadUpsertOne {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateHasAttachments()
	})
}

// Exec executes the query.
func (u *ThreadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ThreadUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ThreadUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ThreadCreateBulk is the builder for creating many Thread entities in bulk.
type ThreadCreateBulk struct {
	config
	err      error
	builders []*ThreadCreate
	conflict []sql.ConflictOption
}

// Save creates the Thread entities in the database.
func (_c *ThreadCreateBulk) Save(ctx context.Context) ([]*Thread, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Thread, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThreadCreateBulk) SaveX(ctx context.Context) []*Thread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Thread.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadUpsert) {
//			SetProviderThreadID(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadCreateBulk) OnConflict(opts ...sql.ConflictOption) *ThreadUpsertBulk {
	_c.conflict = opts
	return &ThreadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadCreateBulk) OnConflictColumns(columns ...string) *ThreadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadUpsertBulk{
		create: _c,
	}
}

// ThreadUpsertBulk is the builder for "upsert"-ing
// a bulk of Thread nodes.
type ThreadUpsertBulk struct {
	create *ThreadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ThreadUpsertBulk) UpdateNewValues() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Thread.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ThreadUpsertBulk) Ignore() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadUpsertBulk) DoNothing() *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadCreateBulk.OnConflict
// documentation for more info.
func (u *ThreadUpsertBulk) Update(set func(*ThreadUpsert)) *ThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderThreadID sets the "provider_thread_id" field.
func (u *ThreadUpsertBulk) SetProviderThreadID(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetProviderThreadID(v)
	})
}

// UpdateProviderThreadID sets the "provider_thread_id" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateProviderThreadID() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateProviderThreadID()
	})
}

// SetSubject sets the "subject" field.
func (u *ThreadUpsertBulk) SetSubject(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateSubject() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSubject()
	})
}

// SetSnippet sets the "snippet" field.
func (u *ThreadUpsertBulk) SetSnippet(v string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSnippet(v)
	})
}

// UpdateSnippet sets the "snippet" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateSnippet() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSnippet()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ThreadUpsertBulk) SetLastMessageAt(v time.Time) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateLastMessageAt() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetParticipants sets the "participants" field.
func (u *ThreadUpsertBulk) SetParticipants(v []string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetParticipants(v)
	})
}

// UpdateParticipants sets the "participants" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateParticipants() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateParticipants()
	})
}

// SetUnread sets the "unread" field.
func (u *ThreadUpsertBulk) SetUnread(v bool) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetUnread(v)
	})
}

// UpdateUnread sets the "unread" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateUnread() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateUnread()
	})
}

// SetStarred sets the "starred" field.
func (u *ThreadUpsertBulk) SetStarred(v bool) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetStarred(v)
	})
}

// UpdateStarred sets the "starred" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateStarred() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateStarred()
	})
}

// SetInInbox sets the "in_inbox" field.
func (u *ThreadUpsertBulk) SetInInbox(v bool) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetInInbox(v)
	})
}

// UpdateInInbox sets the "in_inbox" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateInInbox() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateInInbox()
	})
}

// SetLabels sets the "labels" field.
func (u *ThreadUpsertBulk) SetLabels(v []string) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateLabels() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateLabels()
	})
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (u *ThreadUpsertBulk) SetSnoozedUntil(v time.Time) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetSnoozedUntil(v)
	})
}

// UpdateSnoozedUntil sets the "snoozed_until" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateSnoozedUntil() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateSnoozedUntil()
	})
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (u *ThreadUpsertBulk) ClearSnoozedUntil() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.ClearSnoozedUntil()
	})
}

// SetMessageCount sets the "message_count" field.
func (u *ThreadUpsertBulk) SetMessageCount(v int) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetMessageCount(v)
	})
}

// AddMessageCount adds v to the "message_count" field.
func (u *ThreadUpsertBulk) AddMessageCount(v int) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.AddMessageCount(v)
	})
}

// UpdateMessageCount sets the "message_count" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateMessageCount() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateMessageCount()
	})
}

// SetHasAttachments sets the "has_attachments" field.
func (u *ThreadUpsertBulk) SetHasAttachments(v bool) *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.SetHasAttachments(v)
	})
}

// UpdateHasAttachments sets the "has_attachments" field to the value that was provided on create.
func (u *ThreadUpsertBulk) UpdateHasAttachments() *ThreadUpsertBulk {
	return u.Update(func(s *ThreadUpsert) {
		s.UpdateHasAttachments()
	})
}

// Exec executes the query.
func (u *ThreadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ThreadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
