// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/arqueon/dankmail/core/ent/account"
	"github.com/arqueon/dankmail/core/ent/message"
	"github.com/arqueon/dankmail/core/ent/predicate"
	"github.com/arqueon/dankmail/core/ent/thread"
	"github.com/google/uuid"
)

// ThreadUpdate is the builder for updating Thread entities.
type ThreadUpdate struct {
	config
	hooks     []Hook
	mutation  *ThreadMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ThreadUpdate builder.
func (_u *ThreadUpdate) Where(ps ...predicate.Thread) *ThreadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderThreadID sets the "provider_thread_id" field.
func (_u *ThreadUpdate) SetProviderThreadID(v string) *ThreadUpdate {
	_u.mutation.SetProviderThreadID(v)
	return _u
}

// SetNillableProviderThreadID sets the "provider_thread_id" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableProviderThreadID(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetProviderThreadID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ThreadUpdate) SetSubject(v string) *ThreadUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableSubject(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetSnippet sets the "snippet" field.
func (_u *ThreadUpdate) SetSnippet(v string) *ThreadUpdate {
	_u.mutation.SetSnippet(v)
	return _u
}

// SetNillableSnippet sets the "snippet" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableSnippet(v *string) *ThreadUpdate {
	if v != nil {
		_u.SetSnippet(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ThreadUpdate) SetLastMessageAt(v time.Time) *ThreadUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableLastMessageAt(v *time.Time) *ThreadUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetParticipants sets the "participants" field.
func (_u *ThreadUpdate) SetParticipants(v []string) *ThreadUpdate {
	_u.mutation.SetParticipants(v)
	return _u
}

// AppendParticipants appends value to the "participants" field.
func (_u *ThreadUpdate) AppendParticipants(v []string) *ThreadUpdate {
	_u.mutation.AppendParticipants(v)
	return _u
}

// SetUnread sets the "unread" field.
func (_u *ThreadUpdate) SetUnread(v bool) *ThreadUpdate {
	_u.mutation.SetUnread(v)
	return _u
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableUnread(v *bool) *ThreadUpdate {
	if v != nil {
		_u.SetUnread(*v)
	}
	return _u
}

// SetStarred sets the "starred" field.
func (_u *ThreadUpdate) SetStarred(v bool) *ThreadUpdate {
	_u.mutation.SetStarred(v)
	return _u
}

// SetNillableStarred sets the "starred" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableStarred(v *bool) *ThreadUpdate {
	if v != nil {
		_u.SetStarred(*v)
	}
	return _u
}

// SetInInbox sets the "in_inbox" field.
func (_u *ThreadUpdate) SetInInbox(v bool) *ThreadUpdate {
	_u.mutation.SetInInbox(v)
	return _u
}

// SetNillableInInbox sets the "in_inbox" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableInInbox(v *bool) *ThreadUpdate {
	if v != nil {
		_u.SetInInbox(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *ThreadUpdate) SetLabels(v []string) *ThreadUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *ThreadUpdate) AppendLabels(v []string) *ThreadUpdate {
	_u.mutation.AppendLabels(v)
	return _u
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (_u *ThreadUpdate) SetSnoozedUntil(v time.Time) *ThreadUpdate {
	_u.mutation.SetSnoozedUntil(v)
	return _u
}

// SetNillableSnoozedUntil sets the "snoozed_until" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableSnoozedUntil(v *time.Time) *ThreadUpdate {
	if v != nil {
		_u.SetSnoozedUntil(*v)
	}
	return _u
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (_u *ThreadUpdate) ClearSnoozedUntil() *ThreadUpdate {
	_u.mutation.ClearSnoozedUntil()
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *ThreadUpdate) SetMessageCount(v int) *ThreadUpdate {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *ThreadUpdate) SetNillableMessageCount(v *int) *ThreadUpdate {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *ThreadUpdate) AddMessageCount(v int) *ThreadUpdate {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ThreadUpdate) SetAccountID(id uuid.UUID) *ThreadUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ThreadUpdate) SetAccount(v *Account) *ThreadUpdate {
	return _u.SetAccountID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ThreadUpdate) AddMessageIDs(ids ...int) *ThreadUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ThreadUpdate) AddMessages(v ...*Message) *ThreadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_u *ThreadUpdate) Mutation() *ThreadMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ThreadUpdate) ClearAccount() *ThreadUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ThreadUpdate) ClearMessages() *ThreadUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ThreadUpdate) RemoveMessageIDs(ids ...int) *ThreadUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ThreadUpdate) RemoveMessages(v ...*Message) *ThreadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ThreadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ThreadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThreadUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Thread.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThreadUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThreadUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThreadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderThreadID(); ok {
		_spec.SetField(thread.FieldProviderThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(thread.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snippet(); ok {
		_spec.SetField(thread.FieldSnippet, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(thread.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Participants(); ok {
		_spec.SetField(thread.FieldParticipants, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParticipants(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, thread.FieldParticipants, value)
		})
	}
	if value, ok := _u.mutation.Unread(); ok {
		_spec.SetField(thread.FieldUnread, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Starred(); ok {
		_spec.SetField(thread.FieldStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InInbox(); ok {
		_spec.SetField(thread.FieldInInbox, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(thread.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, thread.FieldLabels, value)
		})
	}
	if value, ok := _u.mutation.SnoozedUntil(); ok {
		_spec.SetField(thread.FieldSnoozedUntil, field.TypeTime, value)
	}
	if _u.mutation.SnoozedUntilCleared() {
		_spec.ClearField(thread.FieldSnoozedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(thread.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(thread.FieldMessageCount, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AccountTable,
			Columns: []string{thread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AccountTable,
			Columns: []string{thread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ThreadUpdateOne is the builder for updating a single Thread entity.
type ThreadUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ThreadMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetProviderThreadID sets the "provider_thread_id" field.
func (_u *ThreadUpdateOne) SetProviderThreadID(v string) *ThreadUpdateOne {
	_u.mutation.SetProviderThreadID(v)
	return _u
}

// SetNillableProviderThreadID sets the "provider_thread_id" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableProviderThreadID(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetProviderThreadID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ThreadUpdateOne) SetSubject(v string) *ThreadUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableSubject(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetSnippet sets the "snippet" field.
func (_u *ThreadUpdateOne) SetSnippet(v string) *ThreadUpdateOne {
	_u.mutation.SetSnippet(v)
	return _u
}

// SetNillableSnippet sets the "snippet" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableSnippet(v *string) *ThreadUpdateOne {
	if v != nil {
		_u.SetSnippet(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ThreadUpdateOne) SetLastMessageAt(v time.Time) *ThreadUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableLastMessageAt(v *time.Time) *ThreadUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetParticipants sets the "participants" field.
func (_u *ThreadUpdateOne) SetParticipants(v []string) *ThreadUpdateOne {
	_u.mutation.SetParticipants(v)
	return _u
}

// AppendParticipants appends value to the "participants" field.
func (_u *ThreadUpdateOne) AppendParticipants(v []string) *ThreadUpdateOne {
	_u.mutation.AppendParticipants(v)
	return _u
}

// SetUnread sets the "unread" field.
func (_u *ThreadUpdateOne) SetUnread(v bool) *ThreadUpdateOne {
	_u.mutation.SetUnread(v)
	return _u
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableUnread(v *bool) *ThreadUpdateOne {
	if v != nil {
		_u.SetUnread(*v)
	}
	return _u
}

// SetStarred sets the "starred" field.
func (_u *ThreadUpdateOne) SetStarred(v bool) *ThreadUpdateOne {
	_u.mutation.SetStarred(v)
	return _u
}

// SetNillableStarred sets the "starred" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableStarred(v *bool) *ThreadUpdateOne {
	if v != nil {
		_u.SetStarred(*v)
	}
	return _u
}

// SetInInbox sets the "in_inbox" field.
func (_u *ThreadUpdateOne) SetInInbox(v bool) *ThreadUpdateOne {
	_u.mutation.SetInInbox(v)
	return _u
}

// SetNillableInInbox sets the "in_inbox" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableInInbox(v *bool) *ThreadUpdateOne {
	if v != nil {
		_u.SetInInbox(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *ThreadUpdateOne) SetLabels(v []string) *ThreadUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *ThreadUpdateOne) AppendLabels(v []string) *ThreadUpdateOne {
	_u.mutation.AppendLabels(v)
	return _u
}

// SetSnoozedUntil sets the "snoozed_until" field.
func (_u *ThreadUpdateOne) SetSnoozedUntil(v time.Time) *ThreadUpdateOne {
	_u.mutation.SetSnoozedUntil(v)
	return _u
}

// SetNillableSnoozedUntil sets the "snoozed_until" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableSnoozedUntil(v *time.Time) *ThreadUpdateOne {
	if v != nil {
		_u.SetSnoozedUntil(*v)
	}
	return _u
}

// ClearSnoozedUntil clears the value of the "snoozed_until" field.
func (_u *ThreadUpdateOne) ClearSnoozedUntil() *ThreadUpdateOne {
	_u.mutation.ClearSnoozedUntil()
	return _u
}

// SetMessageCount sets the "message_count" field.
func (_u *ThreadUpdateOne) SetMessageCount(v int) *ThreadUpdateOne {
	_u.mutation.ResetMessageCount()
	_u.mutation.SetMessageCount(v)
	return _u
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_u *ThreadUpdateOne) SetNillableMessageCount(v *int) *ThreadUpdateOne {
	if v != nil {
		_u.SetMessageCount(*v)
	}
	return _u
}

// AddMessageCount adds value to the "message_count" field.
func (_u *ThreadUpdateOne) AddMessageCount(v int) *ThreadUpdateOne {
	_u.mutation.AddMessageCount(v)
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ThreadUpdateOne) SetAccountID(id uuid.UUID) *ThreadUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ThreadUpdateOne) SetAccount(v *Account) *ThreadUpdateOne {
	return _u.SetAccountID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *ThreadUpdateOne) AddMessageIDs(ids ...int) *ThreadUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *ThreadUpdateOne) AddMessages(v ...*Message) *ThreadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (_u *ThreadUpdateOne) Mutation() *ThreadMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ThreadUpdateOne) ClearAccount() *ThreadUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *ThreadUpdateOne) ClearMessages() *ThreadUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *ThreadUpdateOne) RemoveMessageIDs(ids ...int) *ThreadUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *ThreadUpdateOne) RemoveMessages(v ...*Message) *ThreadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ThreadUpdate builder.
func (_u *ThreadUpdateOne) Where(ps ...predicate.Thread) *ThreadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ThreadUpdateOne) Select(field string, fields ...string) *ThreadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Thread entity.
func (_u *ThreadUpdateOne) Save(ctx context.Context) (*Thread, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadUpdateOne) SaveX(ctx context.Context) *Thread {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThreadUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Thread.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThreadUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThreadUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThreadUpdateOne) sqlSave(ctx context.Context) (_node *Thread, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Thread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thread.FieldID)
		for _, f := range fields {
			if !thread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != thread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderThreadID(); ok {
		_spec.SetField(thread.FieldProviderThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(thread.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snippet(); ok {
		_spec.SetField(thread.FieldSnippet, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(thread.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Participants(); ok {
		_spec.SetField(thread.FieldParticipants, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParticipants(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, thread.FieldParticipants, value)
		})
	}
	if value, ok := _u.mutation.Unread(); ok {
		_spec.SetField(thread.FieldUnread, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Starred(); ok {
		_spec.SetField(thread.FieldStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InInbox(); ok {
		_spec.SetField(thread.FieldInInbox, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(thread.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, thread.FieldLabels, value)
		})
	}
	if value, ok := _u.mutation.SnoozedUntil(); ok {
		_spec.SetField(thread.FieldSnoozedUntil, field.TypeTime, value)
	}
	if _u.mutation.SnoozedUntilCleared() {
		_spec.ClearField(thread.FieldSnoozedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageCount(); ok {
		_spec.SetField(thread.FieldMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageCount(); ok {
		_spec.AddField(thread.FieldMessageCount, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AccountTable,
			Columns: []string{thread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AccountTable,
			Columns: []string{thread.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.MessagesTable,
			Columns: []string{thread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Thread{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
