// Code generated by ent, DO NOT EDIT.

package notifyrule

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the notifyrule type in the database.
	Label = "notify_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotify holds the string denoting the notify field in the database.
	FieldNotify = "notify"
	// FieldSound holds the string denoting the sound field in the database.
	FieldSound = "sound"
	// FieldUrgency holds the string denoting the urgency field in the database.
	FieldUrgency = "urgency"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the notifyrule in the database.
	Table = "notify_rules"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "notify_rules"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_notify_rules"
)

// Columns holds all SQL columns for notifyrule fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldEnabled,
	FieldNotify,
	FieldSound,
	FieldUrgency,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "notify_rules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_notify_rules",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultNotify holds the default value on creation for the "notify" field.
	DefaultNotify bool
	// DefaultSound holds the default value on creation for the "sound" field.
	DefaultSound string
)

// Urgency defines the type for the "urgency" enum field.
type Urgency string

// UrgencyNormal is the default value of the Urgency enum.
const DefaultUrgency = UrgencyNormal

// Urgency values.
const (
	UrgencyLow      Urgency = "low"
	UrgencyNormal   Urgency = "normal"
	UrgencyCritical Urgency = "critical"
)

func (u Urgency) String() string {
	return string(u)
}

// UrgencyValidator is a validator for the "urgency" field enum values. It is called by the builders before save.
func UrgencyValidator(u Urgency) error {
	switch u {
	case UrgencyLow, UrgencyNormal, UrgencyCritical:
		return nil
	default:
		return fmt.Errorf("notifyrule: invalid enum value for urgency field: %q", u)
	}
}

// OrderOption defines the ordering options for the NotifyRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNotify orders the results by the notify field.
func ByNotify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotify, opts...).ToFunc()
}

// BySound orders the results by the sound field.
func BySound(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSound, opts...).ToFunc()
}

// ByUrgency orders the results by the urgency field.
func ByUrgency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUrgency, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
