// Code generated by ent, DO NOT EDIT.

package notifyrule

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/arqueon/dankmail/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLTE(FieldID, id))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldEnabled, v))
}

// Notify applies equality check predicate on the "notify" field. It's identical to NotifyEQ.
func Notify(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldNotify, v))
}

// Sound applies equality check predicate on the "sound" field. It's identical to SoundEQ.
func Sound(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldSound, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldContainsFold(FieldLabel, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldEnabled, v))
}

// NotifyEQ applies the EQ predicate on the "notify" field.
func NotifyEQ(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldNotify, v))
}

// NotifyNEQ applies the NEQ predicate on the "notify" field.
func NotifyNEQ(v bool) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldNotify, v))
}

// SoundEQ applies the EQ predicate on the "sound" field.
func SoundEQ(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldSound, v))
}

// SoundNEQ applies the NEQ predicate on the "sound" field.
func SoundNEQ(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldSound, v))
}

// SoundIn applies the In predicate on the "sound" field.
func SoundIn(vs ...string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldIn(FieldSound, vs...))
}

// SoundNotIn applies the NotIn predicate on the "sound" field.
func SoundNotIn(vs ...string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNotIn(FieldSound, vs...))
}

// SoundGT applies the GT predicate on the "sound" field.
func SoundGT(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGT(FieldSound, v))
}

// SoundGTE applies the GTE predicate on the "sound" field.
func SoundGTE(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldGTE(FieldSound, v))
}

// SoundLT applies the LT predicate on the "sound" field.
func SoundLT(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLT(FieldSound, v))
}

// SoundLTE applies the LTE predicate on the "sound" field.
func SoundLTE(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldLTE(FieldSound, v))
}

// SoundContains applies the Contains predicate on the "sound" field.
func SoundContains(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldContains(FieldSound, v))
}

// SoundHasPrefix applies the HasPrefix predicate on the "sound" field.
func SoundHasPrefix(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldHasPrefix(FieldSound, v))
}

// SoundHasSuffix applies the HasSuffix predicate on the "sound" field.
func SoundHasSuffix(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldHasSuffix(FieldSound, v))
}

// SoundEqualFold applies the EqualFold predicate on the "sound" field.
func SoundEqualFold(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEqualFold(FieldSound, v))
}

// SoundContainsFold applies the ContainsFold predicate on the "sound" field.
func SoundContainsFold(v string) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldContainsFold(FieldSound, v))
}

// UrgencyEQ applies the EQ predicate on the "urgency" field.
func UrgencyEQ(v Urgency) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldEQ(FieldUrgency, v))
}

// UrgencyNEQ applies the NEQ predicate on the "urgency" field.
func UrgencyNEQ(v Urgency) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNEQ(FieldUrgency, v))
}

// UrgencyIn applies the In predicate on the "urgency" field.
func UrgencyIn(vs ...Urgency) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldIn(FieldUrgency, vs...))
}

// UrgencyNotIn applies the NotIn predicate on the "urgency" field.
func UrgencyNotIn(vs ...Urgency) predicate.NotifyRule {
	return predicate.NotifyRule(sql.FieldNotIn(FieldUrgency, vs...))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.NotifyRule {
	return predicate.NotifyRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.NotifyRule {
	return predicate.NotifyRule(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotifyRule) predicate.NotifyRule {
	return predicate.NotifyRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotifyRule) predicate.NotifyRule {
	return predicate.NotifyRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotifyRule) predicate.NotifyRule {
	return predicate.NotifyRule(sql.NotPredicates(p))
}
