// Code generated by ent, DO NOT EDIT.

package pendingop

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pendingop type in the database.
	Label = "pending_op"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderThreadIds holds the string denoting the provider_thread_ids field in the database.
	FieldProviderThreadIds = "provider_thread_ids"
	// FieldOpType holds the string denoting the op_type field in the database.
	FieldOpType = "op_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the pendingop in the database.
	Table = "pending_ops"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "pending_ops"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_pending_ops"
)

// Columns holds all SQL columns for pendingop fields.
var Columns = []string{
	FieldID,
	FieldProviderThreadIds,
	FieldOpType,
	FieldPayload,
	FieldCreatedAt,
	FieldAttempts,
	FieldNextAttemptAt,
	FieldLastError,
	FieldState,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pending_ops"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_pending_ops",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProviderThreadIds holds the default value on creation for the "provider_thread_ids" field.
	DefaultProviderThreadIds []string
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
)

// OpType defines the type for the "op_type" enum field.
type OpType string

// OpType values.
const (
	OpTypeMarkRead   OpType = "mark_read"
	OpTypeMarkUnread OpType = "mark_unread"
	OpTypeStar       OpType = "star"
	OpTypeUnstar     OpType = "unstar"
	OpTypeArchive    OpType = "archive"
	OpTypeUnarchive  OpType = "unarchive"
	OpTypeTrash      OpType = "trash"
	OpTypeUnspam     OpType = "unspam"
	OpTypeSnooze     OpType = "snooze"
	OpTypeSnoozeWake OpType = "snooze_wake"
	OpTypeSendReply  OpType = "send_reply"
	OpTypeCompose    OpType = "compose"
)

func (ot OpType) String() string {
	return string(ot)
}

// OpTypeValidator is a validator for the "op_type" field enum values. It is called by the builders before save.
func OpTypeValidator(ot OpType) error {
	switch ot {
	case OpTypeMarkRead, OpTypeMarkUnread, OpTypeStar, OpTypeUnstar, OpTypeArchive, OpTypeUnarchive, OpTypeTrash, OpTypeUnspam, OpTypeSnooze, OpTypeSnoozeWake, OpTypeSendReply, OpTypeCompose:
		return nil
	default:
		return fmt.Errorf("pendingop: invalid enum value for op_type field: %q", ot)
	}
}

// State defines the type for the "state" enum field.
type State string

// StatePending is the default value of the State enum.
const DefaultState = StatePending

// State values.
const (
	StatePending  State = "pending"
	StateInflight State = "inflight"
	StateDone     State = "done"
	StateFailed   State = "failed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePending, StateInflight, StateDone, StateFailed:
		return nil
	default:
		return fmt.Errorf("pendingop: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the PendingOp queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOpType orders the results by the op_type field.
func ByOpType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
