// Code generated by ent, DO NOT EDIT.

package thread

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the thread type in the database.
	Label = "thread"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderThreadID holds the string denoting the provider_thread_id field in the database.
	FieldProviderThreadID = "provider_thread_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldSnippet holds the string denoting the snippet field in the database.
	FieldSnippet = "snippet"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldParticipants holds the string denoting the participants field in the database.
	FieldParticipants = "participants"
	// FieldUnread holds the string denoting the unread field in the database.
	FieldUnread = "unread"
	// FieldStarred holds the string denoting the starred field in the database.
	FieldStarred = "starred"
	// FieldInInbox holds the string denoting the in_inbox field in the database.
	FieldInInbox = "in_inbox"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldSnoozedUntil holds the string denoting the snoozed_until field in the database.
	FieldSnoozedUntil = "snoozed_until"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// FieldHasAttachments holds the string denoting the has_attachments field in the database.
	FieldHasAttachments = "has_attachments"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the thread in the database.
	Table = "threads"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "threads"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_threads"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "thread_messages"
)

// Columns holds all SQL columns for thread fields.
var Columns = []string{
	FieldID,
	FieldProviderThreadID,
	FieldSubject,
	FieldSnippet,
	FieldLastMessageAt,
	FieldParticipants,
	FieldUnread,
	FieldStarred,
	FieldInInbox,
	FieldLabels,
	FieldSnoozedUntil,
	FieldMessageCount,
	FieldHasAttachments,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "threads"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_threads",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSubject holds the default value on creation for the "subject" field.
	DefaultSubject string
	// DefaultSnippet holds the default value on creation for the "snippet" field.
	DefaultSnippet string
	// DefaultParticipants holds the default value on creation for the "participants" field.
	DefaultParticipants []string
	// DefaultUnread holds the default value on creation for the "unread" field.
	DefaultUnread bool
	// DefaultStarred holds the default value on creation for the "starred" field.
	DefaultStarred bool
	// DefaultInInbox holds the default value on creation for the "in_inbox" field.
	DefaultInInbox bool
	// DefaultLabels holds the default value on creation for the "labels" field.
	DefaultLabels []string
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int
	// DefaultHasAttachments holds the default value on creation for the "has_attachments" field.
	DefaultHasAttachments bool
)

// OrderOption defines the ordering options for the Thread queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderThreadID orders the results by the provider_thread_id field.
func ByProviderThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderThreadID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// BySnippet orders the results by the snippet field.
func BySnippet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnippet, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByUnread orders the results by the unread field.
func ByUnread(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnread, opts...).ToFunc()
}

// ByStarred orders the results by the starred field.
func ByStarred(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarred, opts...).ToFunc()
}

// ByInInbox orders the results by the in_inbox field.
func ByInInbox(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInInbox, opts...).ToFunc()
}

// BySnoozedUntil orders the results by the snoozed_until field.
func BySnoozedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnoozedUntil, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}

// ByHasAttachments orders the results by the has_attachments field.
func ByHasAttachments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasAttachments, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
