// Code generated by ent, DO NOT EDIT.

package thread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/arqueon/dankmail/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldID, id))
}

// ProviderThreadID applies equality check predicate on the "provider_thread_id" field. It's identical to ProviderThreadIDEQ.
func ProviderThreadID(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldProviderThreadID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSubject, v))
}

// Snippet applies equality check predicate on the "snippet" field. It's identical to SnippetEQ.
func Snippet(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSnippet, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldLastMessageAt, v))
}

// Unread applies equality check predicate on the "unread" field. It's identical to UnreadEQ.
func Unread(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldUnread, v))
}

// Starred applies equality check predicate on the "starred" field. It's identical to StarredEQ.
func Starred(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldStarred, v))
}

// InInbox applies equality check predicate on the "in_inbox" field. It's identical to InInboxEQ.
func InInbox(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldInInbox, v))
}

// SnoozedUntil applies equality check predicate on the "snoozed_until" field. It's identical to SnoozedUntilEQ.
func SnoozedUntil(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSnoozedUntil, v))
}

// MessageCount applies equality check predicate on the "message_count" field. It's identical to MessageCountEQ.
func MessageCount(v int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldMessageCount, v))
}

// HasAttachments applies equality check predicate on the "has_attachments" field. It's identical to HasAttachmentsEQ.
func HasAttachments(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldHasAttachments, v))
}

// ProviderThreadIDEQ applies the EQ predicate on the "provider_thread_id" field.
func ProviderThreadIDEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldProviderThreadID, v))
}

// ProviderThreadIDNEQ applies the NEQ predicate on the "provider_thread_id" field.
func ProviderThreadIDNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldProviderThreadID, v))
}

// ProviderThreadIDIn applies the In predicate on the "provider_thread_id" field.
func ProviderThreadIDIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldProviderThreadID, vs...))
}

// ProviderThreadIDNotIn applies the NotIn predicate on the "provider_thread_id" field.
func ProviderThreadIDNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldProviderThreadID, vs...))
}

// ProviderThreadIDGT applies the GT predicate on the "provider_thread_id" field.
func ProviderThreadIDGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldProviderThreadID, v))
}

// ProviderThreadIDGTE applies the GTE predicate on the "provider_thread_id" field.
func ProviderThreadIDGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldProviderThreadID, v))
}

// ProviderThreadIDLT applies the LT predicate on the "provider_thread_id" field.
func ProviderThreadIDLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldProviderThreadID, v))
}

// ProviderThreadIDLTE applies the LTE predicate on the "provider_thread_id" field.
func ProviderThreadIDLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldProviderThreadID, v))
}

// ProviderThreadIDContains applies the Contains predicate on the "provider_thread_id" field.
func ProviderThreadIDContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldProviderThreadID, v))
}

// ProviderThreadIDHasPrefix applies the HasPrefix predicate on the "provider_thread_id" field.
func ProviderThreadIDHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldProviderThreadID, v))
}

// ProviderThreadIDHasSuffix applies the HasSuffix predicate on the "provider_thread_id" field.
func ProviderThreadIDHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldProviderThreadID, v))
}

// ProviderThreadIDEqualFold applies the EqualFold predicate on the "provider_thread_id" field.
func ProviderThreadIDEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldProviderThreadID, v))
}

// ProviderThreadIDContainsFold applies the ContainsFold predicate on the "provider_thread_id" field.
func ProviderThreadIDContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldProviderThreadID, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldSubject, v))
}

// SnippetEQ applies the EQ predicate on the "snippet" field.
func SnippetEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSnippet, v))
}

// SnippetNEQ applies the NEQ predicate on the "snippet" field.
func SnippetNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldSnippet, v))
}

// SnippetIn applies the In predicate on the "snippet" field.
func SnippetIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldSnippet, vs...))
}

// SnippetNotIn applies the NotIn predicate on the "snippet" field.
func SnippetNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldSnippet, vs...))
}

// SnippetGT applies the GT predicate on the "snippet" field.
func SnippetGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldSnippet, v))
}

// SnippetGTE applies the GTE predicate on the "snippet" field.
func SnippetGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldSnippet, v))
}

// SnippetLT applies the LT predicate on the "snippet" field.
func SnippetLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldSnippet, v))
}

// SnippetLTE applies the LTE predicate on the "snippet" field.
func SnippetLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldSnippet, v))
}

// SnippetContains applies the Contains predicate on the "snippet" field.
func SnippetContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldSnippet, v))
}

// SnippetHasPrefix applies the HasPrefix predicate on the "snippet" field.
func SnippetHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldSnippet, v))
}

// SnippetHasSuffix applies the HasSuffix predicate on the "snippet" field.
func SnippetHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldSnippet, v))
}

// SnippetEqualFold applies the EqualFold predicate on the "snippet" field.
func SnippetEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldSnippet, v))
}

// SnippetContainsFold applies the ContainsFold predicate on the "snippet" field.
func SnippetContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldSnippet, v))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldLastMessageAt, v))
}

// UnreadEQ applies the EQ predicate on the "unread" field.
func UnreadEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldUnread, v))
}

// UnreadNEQ applies the NEQ predicate on the "unread" field.
func UnreadNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldUnread, v))
}

// StarredEQ applies the EQ predicate on the "starred" field.
func StarredEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldStarred, v))
}

// StarredNEQ applies the NEQ predicate on the "starred" field.
func StarredNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldStarred, v))
}

// InInboxEQ applies the EQ predicate on the "in_inbox" field.
func InInboxEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldInInbox, v))
}

// InInboxNEQ applies the NEQ predicate on the "in_inbox" field.
func InInboxNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldInInbox, v))
}

// SnoozedUntilEQ applies the EQ predicate on the "snoozed_until" field.
func SnoozedUntilEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldSnoozedUntil, v))
}

// SnoozedUntilNEQ applies the NEQ predicate on the "snoozed_until" field.
func SnoozedUntilNEQ(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldSnoozedUntil, v))
}

// SnoozedUntilIn applies the In predicate on the "snoozed_until" field.
func SnoozedUntilIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldSnoozedUntil, vs...))
}

// SnoozedUntilNotIn applies the NotIn predicate on the "snoozed_until" field.
func SnoozedUntilNotIn(vs ...time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldSnoozedUntil, vs...))
}

// SnoozedUntilGT applies the GT predicate on the "snoozed_until" field.
func SnoozedUntilGT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldSnoozedUntil, v))
}

// SnoozedUntilGTE applies the GTE predicate on the "snoozed_until" field.
func SnoozedUntilGTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldSnoozedUntil, v))
}

// SnoozedUntilLT applies the LT predicate on the "snoozed_until" field.
func SnoozedUntilLT(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldSnoozedUntil, v))
}

// SnoozedUntilLTE applies the LTE predicate on the "snoozed_until" field.
func SnoozedUntilLTE(v time.Time) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldSnoozedUntil, v))
}

// SnoozedUntilIsNil applies the IsNil predicate on the "snoozed_until" field.
func SnoozedUntilIsNil() predicate.Thread {
	return predicate.Thread(sql.FieldIsNull(FieldSnoozedUntil))
}

// SnoozedUntilNotNil applies the NotNil predicate on the "snoozed_until" field.
func SnoozedUntilNotNil() predicate.Thread {
	return predicate.Thread(sql.FieldNotNull(FieldSnoozedUntil))
}

// MessageCountEQ applies the EQ predicate on the "message_count" field.
func MessageCountEQ(v int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldMessageCount, v))
}

// MessageCountNEQ applies the NEQ predicate on the "message_count" field.
func MessageCountNEQ(v int) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldMessageCount, v))
}

// MessageCountIn applies the In predicate on the "message_count" field.
func MessageCountIn(vs ...int) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldMessageCount, vs...))
}

// MessageCountNotIn applies the NotIn predicate on the "message_count" field.
func MessageCountNotIn(vs ...int) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldMessageCount, vs...))
}

// MessageCountGT applies the GT predicate on the "message_count" field.
func MessageCountGT(v int) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldMessageCount, v))
}

// MessageCountGTE applies the GTE predicate on the "message_count" field.
func MessageCountGTE(v int) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldMessageCount, v))
}

// MessageCountLT applies the LT predicate on the "message_count" field.
func MessageCountLT(v int) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldMessageCount, v))
}

// MessageCountLTE applies the LTE predicate on the "message_count" field.
func MessageCountLTE(v int) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldMessageCount, v))
}

// HasAttachmentsEQ applies the EQ predicate on the "has_attachments" field.
func HasAttachmentsEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldHasAttachments, v))
}

// HasAttachmentsNEQ applies the NEQ predicate on the "has_attachments" field.
func HasAttachmentsNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldHasAttachments, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.NotPredicates(p))
}
